In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("train_processed.csv")
df2 = pd.read_csv("train_processed_encoded.csv")

In [3]:
df.head()

Unnamed: 0  Patient Age Genes in mother's side Inherited from father  \
0           0          2.0                    Yes                    No   
1           1          4.0                    Yes                   Yes   
2           2          6.0                    Yes                    No   
3           3         12.0                    Yes                    No   
4           4         11.0                    Yes                    No   

  Maternal gene Paternal gene  Blood cell count (mcL)  Mother's age  \
0           Yes            No                4.760603          23.0   
1            No            No                4.910669          23.0   
2            No            No                4.893297          41.0   
3           Yes            No                4.705280          21.0   
4           Yes           Yes                4.720703          32.0   

   Father's age    Status  ... Birth defects  \
0          20.0     Alive  ...      Singular   
1          23.0  Deceased  ...      Multiple   
2          22.0     Alive  ...      Singular   
3          20.0  Deceased  ...      Singular   
4          20.0     Alive  ...      Multiple   

  White Blood cell count (thousand per microliter)  Blood test result  \
0                                         9.857562  slightly abnormal   
1                                         5.522560             normal   
2                                         7.477132             normal   
3                                         7.919321       inconclusive   
4                                         4.098210  slightly abnormal   

  Symptom 1 Symptom 2 Symptom 3 Symptom 4 Symptom 5  \
0       1.0       1.0       1.0       1.0       1.0   
1       1.0       1.0       1.0       1.0       0.0   
2       0.0       1.0       1.0       1.0       1.0   
3       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0   

                               Genetic Disorder  \
0   Mitochondrial genetic inheritance disorders   
1   Mitochondrial genetic inheritance disorders   
2  Multifactorial genetic inheritance disorders   
3   Mitochondrial genetic inheritance disorders   
4  Multifactorial genetic inheritance disorders   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
1                      Cystic fibrosis  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer  

[5 rows x 31 columns]

In [4]:
df2.head()

Unnamed: 0  Patient Age  Genes in mother's side  Inherited from father  \
0           0          2.0                     1.0                    0.0   
1           1          4.0                     1.0                    1.0   
2           2          6.0                     1.0                    0.0   
3           3         12.0                     1.0                    0.0   
4           4         11.0                     1.0                    0.0   

   Maternal gene  Paternal gene  Blood cell count (mcL)  Mother's age  \
0            1.0            0.0                4.760603           5.0   
1            0.0            0.0                4.910669           5.0   
2            0.0            0.0                4.893297          23.0   
3            1.0            0.0                4.705280           3.0   
4            1.0            1.0                4.720703          14.0   

   Father's age  Status  ...  Birth defects  \
0          20.0     0.0  ...            1.0   
1          23.0     1.0  ...            0.0   
2          22.0     0.0  ...            1.0   
3          20.0     1.0  ...            1.0   
4          20.0     0.0  ...            0.0   

   White Blood cell count (thousand per microliter)  Blood test result  \
0                                          9.857562                3.0   
1                                          5.522560                2.0   
2                                          7.477132                2.0   
3                                          7.919321                1.0   
4                                          4.098210                3.0   

   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  Genetic Disorder  \
0        1.0        1.0        1.0        1.0        1.0               0.0   
1        1.0        1.0        1.0        1.0        0.0               0.0   
2        0.0        1.0        1.0        1.0        1.0               1.0   
3        0.0        0.0        1.0        0.0        0.0               0.0   
4        0.0        0.0        0.0        0.0        0.0               1.0   

   Disorder Subclass  
0                5.0  
1                2.0  
2                3.0  
3                6.0  
4                1.0  

[5 rows x 31 columns]

In [5]:
df = df.iloc[: , 1:]

In [6]:
df2 = df2.iloc[: , 1:]

In [7]:
df2['Disorder+Subclass'] = df['Genetic Disorder'] + ' - ' + df['Disorder Subclass']
df_train = df2.drop(["Genetic Disorder", "Disorder Subclass", "Disorder+Subclass"], axis=1)
df_test_Disorder = df["Genetic Disorder"]
df_test_Subclass = df["Disorder Subclass"]
df_test_Disorder_Subclass = df2["Disorder+Subclass"]


In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_train_encoded = pd.DataFrame(scaler.fit_transform(df_train))

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

def compute_metrics(actual, predicted):
    #tn, fp, fn, tp = confusion_matrix(actual, predicted).ravel()
    print(confusion_matrix(actual, predicted))
    print("Accuracy: " + str(accuracy_score(actual, predicted)))
    print(classification_report(actual, predicted, zero_division=0))

In [10]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df_train_encoded, df_test_Disorder, test_size=0.30, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_train_encoded, df_test_Subclass, test_size=0.30, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(df_train_encoded, df_test_Disorder_Subclass, test_size=0.30, random_state=42)

## Predicting Genetic Disorder

In [11]:
from sklearn.linear_model import LogisticRegression

logRegression = LogisticRegression()
logRegression.fit(X_train1, y_train1)
compute_metrics(y_test1, logRegression.predict(X_test1))

[[3620  109    0]
 [ 538  116    0]
 [2192   50    0]]
Accuracy: 0.5639245283018868
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.57      0.97      0.72      3729
Multifactorial genetic inheritance disorders       0.42      0.18      0.25       654
            Single-gene inheritance diseases       0.00      0.00      0.00      2242

                                    accuracy                           0.56      6625
                                   macro avg       0.33      0.38      0.32      6625
                                weighted avg       0.36      0.56      0.43      6625



In [12]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train1, y_train1)
compute_metrics(y_test1, decisionTree.predict(X_test1))

[[2247  289 1193]
 [ 253  180  221]
 [1116  229  897]]
Accuracy: 0.5017358490566037
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.62      0.60      0.61      3729
Multifactorial genetic inheritance disorders       0.26      0.28      0.27       654
            Single-gene inheritance diseases       0.39      0.40      0.39      2242

                                    accuracy                           0.50      6625
                                   macro avg       0.42      0.43      0.42      6625
                                weighted avg       0.51      0.50      0.50      6625



In [13]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(X_train1, y_train1)
compute_metrics(y_test1, randomForest.predict(X_test1))

[[3340   67  322]
 [ 404   99  151]
 [1713   40  489]]
Accuracy: 0.5929056603773585
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.61      0.90      0.73      3729
Multifactorial genetic inheritance disorders       0.48      0.15      0.23       654
            Single-gene inheritance diseases       0.51      0.22      0.31      2242

                                    accuracy                           0.59      6625
                                   macro avg       0.53      0.42      0.42      6625
                                weighted avg       0.56      0.59      0.54      6625



In [14]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_train1, y_train1)
compute_metrics(y_test1, clf.predict(X_test1))

[[2664  176  889]
 [ 227  191  236]
 [1139  144  959]]
Accuracy: 0.5756981132075472
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.66      0.71      0.69      3729
Multifactorial genetic inheritance disorders       0.37      0.29      0.33       654
            Single-gene inheritance diseases       0.46      0.43      0.44      2242

                                    accuracy                           0.58      6625
                                   macro avg       0.50      0.48      0.49      6625
                                weighted avg       0.56      0.58      0.57      6625



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [15]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train1, y_train1)
compute_metrics(y_test1, svc.predict(X_test1))

[[3406  103  220]
 [ 447  124   83]
 [1823   53  366]]
Accuracy: 0.5880754716981133
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.60      0.91      0.72      3729
Multifactorial genetic inheritance disorders       0.44      0.19      0.27       654
            Single-gene inheritance diseases       0.55      0.16      0.25      2242

                                    accuracy                           0.59      6625
                                   macro avg       0.53      0.42      0.41      6625
                                weighted avg       0.57      0.59      0.52      6625



## Predicting Subclass

In [16]:
logRegression = LogisticRegression()
logRegression.fit(X_train2, y_train2)
compute_metrics(y_test2, logRegression.predict(X_test2))

[[   4    0   10   18    0   10    3    0    0]
 [   0    0    0    0   22    0    1    1    9]
 [   0    0  459   57    0    6  474    6    4]
 [   0    0  344   94    0   13  128    0    2]
 [   0    4    0    0   93    0   73   53  170]
 [   0    0  102   57    0   30   22    0    0]
 [   0    0  254   30   26    2 1586  163  120]
 [   0    0   30    1   21    0  875  235  176]
 [   0    0    3    0   54    0  355  181  244]]
Accuracy: 0.4143396226415094
                                     precision    recall  f1-score   support

                        Alzheimer's       1.00      0.09      0.16        45
                             Cancer       0.00      0.00      0.00        33
                    Cystic fibrosis       0.38      0.46      0.42      1006
                           Diabetes       0.37      0.16      0.22       581
                    Hemochromatosis       0.43      0.24      0.31       393
Leber's hereditary optic neuropathy       0.49      0.14      0.22       21

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train2, y_train2)
compute_metrics(y_test2, decisionTree.predict(X_test2))

[[  6   0   9  12   0  11   4   2   1]
 [  0   4   0   0  12   0   3   3  11]
 [ 11   0 295 178   9  65 310 108  30]
 [ 16   0 187 142   1  56 131  41   7]
 [  0  12   8   0  83   0 104  85 101]
 [ 10   0  69  59   1  36  28   5   3]
 [  9   8 341 164 101  41 774 491 252]
 [  2   2 126  39 124   8 446 356 235]
 [  1   3  32  10 118   2 238 233 200]]
Accuracy: 0.286188679245283
                                     precision    recall  f1-score   support

                        Alzheimer's       0.11      0.13      0.12        45
                             Cancer       0.14      0.12      0.13        33
                    Cystic fibrosis       0.28      0.29      0.28      1006
                           Diabetes       0.24      0.24      0.24       581
                    Hemochromatosis       0.18      0.21      0.20       393
Leber's hereditary optic neuropathy       0.16      0.17      0.17       211
                     Leigh syndrome       0.38      0.35      0.37      2181
   

In [18]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train2, y_train2)
compute_metrics(y_test2, randomForest.predict(X_test2))

[[   0    0   18   22    0    2    3    0    0]
 [   0    0    0    0   15    0    9    2    7]
 [   0    0  388   64    0    2  522   28    2]
 [   0    0  286   96    0    8  188    3    0]
 [   0    0    0    0   61    0  133   84  115]
 [   1    0  102   62    0   12   32    2    0]
 [   0    0  248   33   19    2 1554  236   89]
 [   0    0   28    5   13    0  954  229  109]
 [   0    0    5    0   37    0  443  200  152]]
Accuracy: 0.3761509433962264
                                     precision    recall  f1-score   support

                        Alzheimer's       0.00      0.00      0.00        45
                             Cancer       0.00      0.00      0.00        33
                    Cystic fibrosis       0.36      0.39      0.37      1006
                           Diabetes       0.34      0.17      0.22       581
                    Hemochromatosis       0.42      0.16      0.23       393
Leber's hereditary optic neuropathy       0.46      0.06      0.10       21

In [19]:
mlp = MLPClassifier()
mlp.fit(X_train2, y_train2)
compute_metrics(y_test2, mlp.predict(X_test2))

[[  11    0   15    8    0    9    2    0    0]
 [   0    5    0    0   16    0    3    3    6]
 [   3    0  453  120    1   24  362   38    5]
 [   9    0  266  119    0   37  142    6    2]
 [   0    5    1    1  103    0   70   69  144]
 [   6    0   79   56    0   46   24    0    0]
 [   4    0  303   62   39   12 1201  397  163]
 [   0    0   76    6   56    0  663  311  226]
 [   0    0    9    0   82    0  286  237  223]]
Accuracy: 0.37313207547169813
                                     precision    recall  f1-score   support

                        Alzheimer's       0.33      0.24      0.28        45
                             Cancer       0.50      0.15      0.23        33
                    Cystic fibrosis       0.38      0.45      0.41      1006
                           Diabetes       0.32      0.20      0.25       581
                    Hemochromatosis       0.35      0.26      0.30       393
Leber's hereditary optic neuropathy       0.36      0.22      0.27       2

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
svc = SVC()
svc.fit(X_train2, y_train2)
compute_metrics(y_test2, svc.predict(X_test2))

[[   0    0   10   32    0    0    3    0    0]
 [   0    0    0    0   16    0    4    2   11]
 [   0    0  462   53    0    0  469   21    1]
 [   0    0  324  100    0    1  155    0    1]
 [   0    0    0    0   75    0  109   63  146]
 [   0    0  117   67    0    2   25    0    0]
 [   0    0  290   24   19    0 1553  188  107]
 [   0    0   41    0   16    0  917  203  161]
 [   0    0    4    0   31    0  427  175  200]]
Accuracy: 0.39169811320754716
                                     precision    recall  f1-score   support

                        Alzheimer's       0.00      0.00      0.00        45
                             Cancer       0.00      0.00      0.00        33
                    Cystic fibrosis       0.37      0.46      0.41      1006
                           Diabetes       0.36      0.17      0.23       581
                    Hemochromatosis       0.48      0.19      0.27       393
Leber's hereditary optic neuropathy       0.67      0.01      0.02       2

# Predicting Disorder + Subclass

In [21]:
logRegression = LogisticRegression()
logRegression.fit(X_train3, y_train3)
compute_metrics(y_test3, logRegression.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[   0    0    0    0    0    2    2    0    0    0    0    2    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     2    0    1]
 [   0    0    0    0    0    2   42    2    0    0    0    5    0   37
     0    0    0]
 [   0    0    0    0    0    2    8    0    0    0    0    6    0   31
     0    0    0]
 [   0    0    0    0    0    0    7    9    0    0    0    0    0    0
    11    0   14]
 [   0    0    0    0    0   33   18    0    0    1    0   58    0  101
     0    0    0]
 [   0    0    0    0    0    1 1377  242    0    0    0   15    0  201
    12    0   68]
 [   0    0    0    0    0    0  787  363    0    0    0    1    0   36
    24    0  127]
 [   0    0    0    0    0    0   32   25    0    0    0    0    0    0
     6    0   16]
 [   0    0    0    0    0   12    1    0    0    2    0   15    0    9
     0    0    0]
 [   0    0    0    0    0    0    1    3    0    0    2    0    0    0
    19    0    5]
 [   0    

In [22]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train3, y_train3)
compute_metrics(y_test3, decisionTree.predict(X_test3))

[[  0   0   1   0   0   1   0   0   0   0   0   2   0   2   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   1   0   1]
 [  0   0   1   0   0   3  37  14   0   0   0   9   1  14   1   5   3]
 [  0   0   1   0   0   6   8   3   0   1   0   8   1  16   0   1   2]
 [  0   0   1   0   1   0   7  10   1   0   2   0   0   1   9   2   7]
 [  1   0   6   6   0  38  22   5   1  12   0  47   5  60   0   4   4]
 [  0   0  30  14   4  22 714 404  32   3   3  85  17 249  72  60 207]
 [  0   0  12   1  10   5 475 341  32   0   2  36   7  81  89  57 190]
 [  0   0   0   1   0   0  15  30   0   0   0   1   0   3  11   4  14]
 [  0   0   0   0   0   6   2   0   0   4   0  15   0   9   0   3   0]
 [  0   0   0   0   1   0   5   3   2   0   5   0   0   1   3   2   8]
 [  2   0  20  13   0  47 101  33   0  18   0 100  16 160   1  17   6]
 [  0   0   1   1   0   3   4   5   0   5   0  14   2  14   0   0   2]
 [  1   0  23  13   2  47 248  73   3   8   1 156  15 261   6  34  27]
 [  0 

In [23]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train3, y_train3)
compute_metrics(y_test3, randomForest.predict(X_test3))

[[   0    0    0    0    0    0    1    0    0    0    0    3    0    2
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     2    0    1]
 [   0    0    0    0    0    0   47    7    0    0    0    7    0   27
     0    0    0]
 [   0    0    0    0    0    2   15    0    0    0    0   10    0   20
     0    0    0]
 [   0    0    0    0    0    0   12   13    0    0    0    0    0    0
     7    0    9]
 [   0    0    0    0    0   19   31    0    0    0    0   65    0   96
     0    0    0]
 [   0    0    0    0    0    2 1343  302    0    0    0   22    0  183
     9    1   54]
 [   0    0    0    0    0    0  836  313    0    0    0    4    0   41
    20    0  124]
 [   0    0    0    0    0    0   41   21    0    0    0    0    0    0
     5    0   12]
 [   0    0    0    0    0    4    1    0    0    0    0   19    0   15
     0    0    0]
 [   0    0    0    0    0    0    3    4    0    0    0    0    0    0
    16    0    7]
 [   0    

In [24]:
mlp = MLPClassifier()
mlp.fit(X_train3, y_train3)
compute_metrics(y_test3, mlp.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[   0    0    0    0    0    1    1    0    0    1    0    2    0    1
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     1    1    1]
 [   0    0    1    0    0    0   44    6    0    0    0    7    1   28
     0    0    1]
 [   0    0    0    0    0    7    9    1    0    0    0   11    1   17
     0    1    0]
 [   0    0    0    0    0    0    4   14    0    0    1    0    0    0
    11    0   11]
 [   1    0    1    0    0   48   20    0    0    7    0   62    2   70
     0    0    0]
 [   0    0    1    0    0   10 1062  432    3    0    0   42    2  228
    29    6  101]
 [   0    0    0    0    0    0  625  414    2    0    0   11    0   58
    50    4  174]
 [   0    0    0    0    0    0   26   29    0    0    0    0    0    0
     7    0   17]
 [   0    0    0    0    0   11    1    0    0    5    0   16    0    6
     0    0    0]
 [   0    0    0    0    0    0    2    3    0    0    2    0    0    0
    15    1    7]
 [   0    

In [25]:
svc = SVC()
svc.fit(X_train3, y_train3)
compute_metrics(y_test3, svc.predict(X_test3))

[[   0    0    0    0    0    0    1    0    0    0    0    3    0    2
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     1    0    2]
 [   0    0    0    0    0    0   42    4    0    0    0    4    0   38
     0    0    0]
 [   0    0    0    0    0    0   10    0    0    0    0    9    0   28
     0    0    0]
 [   0    0    0    0    0    0    9   13    0    0    0    0    0    0
     8    0   11]
 [   0    0    0    0    0    5   22    0    0    0    0   69    0  115
     0    0    0]
 [   0    0    0    0    0    0 1298  305    0    0    0   16    0  224
     9    0   64]
 [   0    0    0    0    0    0  793  347    0    0    0    1    0   46
    13    0  138]
 [   0    0    0    0    0    0   35   24    0    0    0    0    0    0
     2    0   18]
 [   0    0    0    0    0    0    1    0    0    0    0   27    0   11
     0    0    0]
 [   0    0    0    0    0    0    2    4    0    0    0    0    0    0
    16    0    8]
 [   0    