In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [56]:
#df = pd.read_csv("train_processed.csv")
df2 = pd.read_csv("./data/train_processed_encoded_balanced.csv", index_col=0)
X = pd.read_csv('./data/x.csv', index_col=0)
y_ds_un= pd.read_csv('./data/y_ds.csv', index_col=0)
X_gd = pd.read_csv('./data/x_gd_resampled.csv', index_col=0)
y_gd = pd.read_csv('./data/y_gd_resampled.csv', index_col=0)
X_ds = pd.read_csv('./data/x_ds_resampled.csv', index_col=0)
y_ds = pd.read_csv('./data/y_ds_resampled.csv', index_col=0)
X_ds2 = pd.read_csv('./data/x_ds+gd_edit_resampled.csv', index_col=0)
y_ds2 = pd.read_csv('./data/y_ds+gd_edit_resampled.csv', index_col=0)
X_gdds = pd.read_csv('./data/x_gdds_resampled.csv', index_col=0)
y_gdds = pd.read_csv('./data/y_gdds_resampled.csv', index_col=0)
X_gdds2 = pd.read_csv('./data/x_gdds2_edit_resampled.csv', index_col=0)
y_gdds2 = pd.read_csv('./data/y_gdds2_edit_resampled.csv', index_col=0)

In [58]:
X.head()

Patient Age  Genes in mother's side  Inherited from father  Maternal gene  \
0    -1.128463                0.829238              -0.797596       0.802715   
1    -0.657008                0.829238               1.253709      -1.245714   
2    -0.185554                0.829238              -0.797596      -1.245714   
3     1.228809                0.829238              -0.797596       0.802715   
4     1.700263                0.829238              -0.797596       0.802715   

   Paternal gene  Blood cell count (mcL)  Mother's age  Father's age  \
0      -0.870854               -0.693956     -0.853643     -1.086047   
1      -0.870854                0.057669     -0.853643     -0.883431   
2      -0.870854               -0.029341      0.973622     -0.950970   
3      -0.870854               -0.971047     -1.056673     -1.086047   
4      -0.870854                1.021928     -0.853643     -1.086047   

     Status  Respiratory Rate (breaths/min)  ...  \
0 -0.998339                       -0.900493  ...   
1  1.001617                        1.110451  ...   
2 -0.998339                       -0.900493  ...   
3  1.001617                        1.110451  ...   
4  1.001617                       -0.900493  ...   

   History of anomalies in previous pregnancies  No. of previous abortion  \
0                                      0.897342                  0.000035   
1                                      0.897342                  0.000035   
2                                      0.897342                  1.490541   
3                                      0.897342                 -0.745218   
4                                     -1.114351                 -1.490472   

   Birth defects  White Blood cell count (thousand per microliter)  \
0       0.908367                                          0.942378   
1      -1.100825                                         -0.777460   
2       0.908367                                         -0.002017   
3       0.908367                                          0.173414   
4      -1.100825                                          1.106891   

   Blood test result  Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  
0           1.162632   0.766328   0.827148   0.857458   1.112873   1.192865  
1           0.294673   0.766328   0.827148   0.857458   1.112873  -0.838278  
2           0.294673  -1.304863   0.827148   0.857458   1.112873   1.192865  
3          -0.573287  -1.304863  -1.208916   0.857458  -0.898533  -0.838278  
4           0.294673   0.766328  -1.208916  -1.166184   1.112873  -0.838278  

[5 rows x 28 columns]

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

def compute_metrics(actual, predicted):
    #tn, fp, fn, tp = confusion_matrix(actual, predicted).ravel()
    print(confusion_matrix(actual, predicted))
    print("Accuracy: " + str(accuracy_score(actual, predicted)))
    print(classification_report(actual, predicted, zero_division=0))

In [60]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_gd, y_gd, test_size=0.30, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_ds, y_ds, test_size=0.30, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X_gdds, y_gdds, test_size=0.30, random_state=42)

## Predicting Genetic Disorder

In [61]:
from sklearn.linear_model import LogisticRegression

logRegression = LogisticRegression()
logRegression.fit(X_train1, y_train1)
compute_metrics(y_test1, logRegression.predict(X_test1))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 881  335 1074]
 [ 212 2004  108]
 [ 624  615 1045]]
Accuracy: 0.5697303566251087
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.51      0.38      0.44      2290
Multifactorial genetic inheritance disorders       0.68      0.86      0.76      2324
            Single-gene inheritance diseases       0.47      0.46      0.46      2284

                                    accuracy                           0.57      6898
                                   macro avg       0.55      0.57      0.55      6898
                                weighted avg       0.55      0.57      0.56      6898



In [62]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train1, y_train1)
compute_metrics(y_test1, decisionTree.predict(X_test1))

[[1177  195  918]
 [ 184 1884  256]
 [ 924  261 1099]]
Accuracy: 0.6030733545955349
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.52      0.51      0.51      2290
Multifactorial genetic inheritance disorders       0.81      0.81      0.81      2324
            Single-gene inheritance diseases       0.48      0.48      0.48      2284

                                    accuracy                           0.60      6898
                                   macro avg       0.60      0.60      0.60      6898
                                weighted avg       0.60      0.60      0.60      6898



In [63]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(X_train1, y_train1)
compute_metrics(y_test1, randomForest.predict(X_test1))

<ipython-input-63-83cc24ab388d>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomForest.fit(X_train1, y_train1)


[[1472  108  710]
 [  92 2094  138]
 [ 946  191 1147]]
Accuracy: 0.683241519280951
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.59      0.64      0.61      2290
Multifactorial genetic inheritance disorders       0.88      0.90      0.89      2324
            Single-gene inheritance diseases       0.57      0.50      0.54      2284

                                    accuracy                           0.68      6898
                                   macro avg       0.68      0.68      0.68      6898
                                weighted avg       0.68      0.68      0.68      6898



In [64]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_train1, y_train1)
compute_metrics(y_test1, clf.predict(X_test1))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1075: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[1288  189  813]
 [  74 2103  147]
 [ 727  287 1270]]
Accuracy: 0.6757031023485068
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.62      0.56      0.59      2290
Multifactorial genetic inheritance disorders       0.82      0.90      0.86      2324
            Single-gene inheritance diseases       0.57      0.56      0.56      2284

                                    accuracy                           0.68      6898
                                   macro avg       0.67      0.67      0.67      6898
                                weighted avg       0.67      0.68      0.67      6898



In [65]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train1, y_train1)
compute_metrics(y_test1, svc.predict(X_test1))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1535  176  579]
 [ 126 2089  109]
 [1008  320  956]]
Accuracy: 0.6639605682806611
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.58      0.67      0.62      2290
Multifactorial genetic inheritance disorders       0.81      0.90      0.85      2324
            Single-gene inheritance diseases       0.58      0.42      0.49      2284

                                    accuracy                           0.66      6898
                                   macro avg       0.65      0.66      0.65      6898
                                weighted avg       0.66      0.66      0.65      6898



## Predicting Subclass

In [66]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_train2, y_train2 = over_sampler.fit_resample(X_train2, y_train2)

In [67]:
logRegression = LogisticRegression()
logRegression.fit(X_train2, y_train2)
compute_metrics(y_test2, logRegression.predict(X_test2))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[402 168   3 133 141  30  10]
 [231 285   3 312  56   6   3]
 [  1   0 653   0  22  64 214]
 [ 68 181   0 623  14   0   2]
 [179  38  59  22 319 174 107]
 [ 71  11 132   2 267 219 217]
 [  8   2 308   0  91 174 275]]
Accuracy: 0.44063492063492066
                                     precision    recall  f1-score   support

                    Cystic fibrosis       0.42      0.45      0.44       887
                           Diabetes       0.42      0.32      0.36       896
                    Hemochromatosis       0.56      0.68      0.62       954
Leber's hereditary optic neuropathy       0.57      0.70      0.63       888
                     Leigh syndrome       0.35      0.36      0.35       898
             Mitochondrial myopathy       0.33      0.24      0.28       919
                          Tay-Sachs       0.33      0.32      0.33       858

                           accuracy                           0.44      6300
                          macro avg       0.43      0.44 

In [68]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train2, y_train2)
compute_metrics(y_test2, decisionTree.predict(X_test2))

[[319 195  14  83 162  84  30]
 [181 426   9 162  70  36  12]
 [  7  13 603   2  65 111 153]
 [ 55 120   1 683  20   8   1]
 [180  69  55  26 217 202 149]
 [108  26  73  10 207 234 261]
 [ 33  17 159   3 144 200 302]]
Accuracy: 0.4419047619047619
                                     precision    recall  f1-score   support

                    Cystic fibrosis       0.36      0.36      0.36       887
                           Diabetes       0.49      0.48      0.48       896
                    Hemochromatosis       0.66      0.63      0.65       954
Leber's hereditary optic neuropathy       0.70      0.77      0.74       888
                     Leigh syndrome       0.25      0.24      0.24       898
             Mitochondrial myopathy       0.27      0.25      0.26       919
                          Tay-Sachs       0.33      0.35      0.34       858

                           accuracy                           0.44      6300
                          macro avg       0.44      0.44  

In [69]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train2, y_train2)
compute_metrics(y_test2, randomForest.predict(X_test2))

<ipython-input-69-528c26c4d368>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomForest.fit(X_train2, y_train2)


[[489 164   0  38 126  46  24]
 [182 539   3 113  33  18   8]
 [  0   2 748   0  15  43 146]
 [ 54  44   0 780   7   2   1]
 [211  30  29   8 229 223 168]
 [ 95  10  50   0 194 267 303]
 [ 24   1 127   0  88 193 425]]
Accuracy: 0.5519047619047619
                                     precision    recall  f1-score   support

                    Cystic fibrosis       0.46      0.55      0.50       887
                           Diabetes       0.68      0.60      0.64       896
                    Hemochromatosis       0.78      0.78      0.78       954
Leber's hereditary optic neuropathy       0.83      0.88      0.85       888
                     Leigh syndrome       0.33      0.26      0.29       898
             Mitochondrial myopathy       0.34      0.29      0.31       919
                          Tay-Sachs       0.40      0.50      0.44       858

                           accuracy                           0.55      6300
                          macro avg       0.55      0.55  

In [70]:
mlp = MLPClassifier()
mlp.fit(X_train2, y_train2)
compute_metrics(y_test2, mlp.predict(X_test2))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1075: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[349 238   5  88 150  39  18]
 [199 494   3 129  52  13   6]
 [  3   2 709   0  23  46 171]
 [ 59  87   1 733   7   0   1]
 [162  67  61  22 269 175 142]
 [ 65  23 112   7 222 204 286]
 [ 13   6 217   0 107 140 375]]
Accuracy: 0.4973015873015873
                                     precision    recall  f1-score   support

                    Cystic fibrosis       0.41      0.39      0.40       887
                           Diabetes       0.54      0.55      0.54       896
                    Hemochromatosis       0.64      0.74      0.69       954
Leber's hereditary optic neuropathy       0.75      0.83      0.79       888
                     Leigh syndrome       0.32      0.30      0.31       898
             Mitochondrial myopathy       0.33      0.22      0.27       919
                          Tay-Sachs       0.38      0.44      0.40       858

                           accuracy                           0.50      6300
                          macro avg       0.48      0.50  

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [71]:
svc = SVC()
svc.fit(X_train2, y_train2)
compute_metrics(y_test2, svc.predict(X_test2))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[477 170   1  53 122  49  15]
 [212 501   2 119  47   8   7]
 [  1   0 717   0  20  45 171]
 [ 51  60   0 762  12   1   2]
 [197  38  41  15 262 223 122]
 [ 85  13  91   1 230 247 252]
 [ 20   2 180   0  98 176 382]]
Accuracy: 0.5314285714285715
                                     precision    recall  f1-score   support

                    Cystic fibrosis       0.46      0.54      0.49       887
                           Diabetes       0.64      0.56      0.60       896
                    Hemochromatosis       0.69      0.75      0.72       954
Leber's hereditary optic neuropathy       0.80      0.86      0.83       888
                     Leigh syndrome       0.33      0.29      0.31       898
             Mitochondrial myopathy       0.33      0.27      0.30       919
                          Tay-Sachs       0.40      0.45      0.42       858

                           accuracy                           0.53      6300
                          macro avg       0.52      0.53  

# Predicting Disorder + Subclass

In [72]:
logRegression = LogisticRegression()
logRegression.fit(X_train3, y_train3)
compute_metrics(y_test3, logRegression.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 73  27  67  18   5  92 128   0   7   1]
 [  8 202   5   0   0 168  39   0   1   1]
 [ 37   6 218 116  35  20 100   7  29  59]
 [ 14   0 181 155  50   5  36  27  35 130]
 [  1   0  32  69 112   0   1  49  16 136]
 [ 45 118  30   3   4 283 150   1   6   2]
 [ 41  43 116  20   1 166 217   0  10  10]
 [  0   0  10  31  67   0   1 165   3 151]
 [ 18   8  63  47  36  47  65  49  15  77]
 [  2   0  75 111  64   1   5  93  25 237]]
Accuracy: 0.31942857142857145
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.31      0.17      0.22       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.50      0.48      0.49       424
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.27      0.35      0.31       627
             Mitochondrial genetic inheritance

In [73]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train3, y_train3)
compute_metrics(y_test3, decisionTree.predict(X_test3))

[[224  38  21  13  12  33  26   3  44   4]
 [ 24 212  11   2   1  93  63   0  17   1]
 [ 25  22 129 133  15  49 100  31  37  86]
 [ 18   3 142 134  14  28  58  56  45 135]
 [  9   2  15  19 273   2   1  29  34  32]
 [ 55  99  40  24   4 218 148   7  42   5]
 [ 38  52  88  62   7 124 179   8  45  21]
 [  3   0  32  74  32   0   4 130  43 110]
 [ 30  16  29  45  46  40  31  43 107  38]
 [  5   2  97 134  22   8  22 128  36 159]]
Accuracy: 0.3361904761904762
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.52      0.54      0.53       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.48      0.50      0.49       424
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.21      0.21      0.21       627
             Mitochondrial genetic inheritance 

In [74]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train3, y_train3)
compute_metrics(y_test3, randomForest.predict(X_test3))

<ipython-input-74-fcefb1d5c135>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomForest.fit(X_train3, y_train3)


[[336   8  17   6   7  17  20   0   1   6]
 [ 13 281   6   3   0  77  43   0   1   0]
 [  0   2 204 148   1  28 128  11   4 101]
 [  0   0 165 182   2  12  53  36   1 182]
 [  1   0  10  15 360   0   0   8   1  21]
 [ 19  48  34  13   4 351 165   2   1   5]
 [  3  16 102  36   1 169 279   1   1  16]
 [  0   0  16  54  24   0   3 160   2 169]
 [ 23   9  40  34  29  29  42  22 138  59]
 [  0   0  92 129   4   1  11 101   0 275]]
Accuracy: 0.4887619047619048
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.85      0.80      0.83       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.77      0.66      0.71       424
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.30      0.33      0.31       627
             Mitochondrial genetic inheritance 

In [75]:
mlp = MLPClassifier()
mlp.fit(X_train3, y_train3)
compute_metrics(y_test3, mlp.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1075: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[309  11  18   6   4  20  34   0   9   7]
 [ 12 237   6   0   0 111  47   0  10   1]
 [ 39   6 147 131  24  28 107  18  44  83]
 [ 18   3 144 131  37  12  39  38  48 163]
 [  3   0   3  16 338   0   0  15  16  25]
 [ 43 107  33   4   5 231 195   2  17   5]
 [ 48  62  93  31   3 131 208   2  34  12]
 [  0   0  17  28  53   1   0 144  31 154]
 [  9  15  56  40  30  31  50  41  89  64]
 [  5   0  66 112  43   1  15  88  51 232]]
Accuracy: 0.3935238095238095
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.64      0.74      0.68       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.54      0.56      0.55       424
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.25      0.23      0.24       627
             Mitochondrial genetic inheritance 

In [76]:
svc = SVC()
svc.fit(X_train3, y_train3)
compute_metrics(y_test3, svc.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[325   5  23  11   2  23  26   0   2   1]
 [  6 264   8   1   0 104  39   0   2   0]
 [  7   5 234 148   6  25 107  11  11  73]
 [  2   0 196 170  11   7  46  19  13 169]
 [  2   0   9  18 339   0   1  13   2  32]
 [ 10  76  42   3   2 325 177   2   1   4]
 [  7  27 129  30   1 144 271   0   6   9]
 [  0   0  19  41  29   0   2 157   5 175]
 [ 11   7  59  34  26  40  51  51  82  64]
 [  2   0  93 135  14   0  10  97   9 253]]
Accuracy: 0.46095238095238095
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.87      0.78      0.82       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.69      0.62      0.65       424
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.29      0.37      0.33       627
             Mitochondrial genetic inheritance