In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [38]:
#df = pd.read_csv("train_processed.csv")
df2 = pd.read_csv("train_processed_encoded_balanced.csv")

In [39]:
df.head()

Unnamed: 0  Patient Age Genes in mother's side Inherited from father  \
0           0          2.0                    Yes                    No   
1           1          4.0                    Yes                   Yes   
2           2          6.0                    Yes                    No   
3           3         12.0                    Yes                    No   
4           4         11.0                    Yes                    No   

  Maternal gene Paternal gene  Blood cell count (mcL)  Mother's age  \
0           Yes            No                4.760603          23.0   
1            No            No                4.910669          23.0   
2            No            No                4.893297          41.0   
3           Yes            No                4.705280          21.0   
4           Yes           Yes                4.720703          32.0   

   Father's age    Status  ... Birth defects  \
0          20.0     Alive  ...      Singular   
1          23.0  Deceased  ...      Multiple   
2          22.0     Alive  ...      Singular   
3          20.0  Deceased  ...      Singular   
4          20.0     Alive  ...      Multiple   

  White Blood cell count (thousand per microliter)  Blood test result  \
0                                         9.857562  slightly abnormal   
1                                         5.522560             normal   
2                                         7.477132             normal   
3                                         7.919321       inconclusive   
4                                         4.098210  slightly abnormal   

  Symptom 1 Symptom 2 Symptom 3 Symptom 4 Symptom 5  \
0       1.0       1.0       1.0       1.0       1.0   
1       1.0       1.0       1.0       1.0       0.0   
2       0.0       1.0       1.0       1.0       1.0   
3       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0   

                               Genetic Disorder  \
0   Mitochondrial genetic inheritance disorders   
1   Mitochondrial genetic inheritance disorders   
2  Multifactorial genetic inheritance disorders   
3   Mitochondrial genetic inheritance disorders   
4  Multifactorial genetic inheritance disorders   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
1                      Cystic fibrosis  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer  

[5 rows x 31 columns]

In [40]:
df2.head()

Unnamed: 0  Patient Age  Genes in mother's side  Inherited from father  \
0           1          4.0                     1.0                    1.0   
1           2          6.0                     1.0                    0.0   
2           3         12.0                     1.0                    0.0   
3           5         14.0                     1.0                    0.0   
4           6          3.0                     1.0                    0.0   

   Maternal gene  Paternal gene  Blood cell count (mcL)  Mother's age  \
0            0.0            0.0                4.910669           5.0   
1            0.0            0.0                4.893297          23.0   
2            1.0            0.0                4.705280           3.0   
3            1.0            0.0                5.103188           5.0   
4            1.0            1.0                4.901080           5.0   

   Father's age  Status  ...  Birth defects  \
0          23.0     1.0  ...            0.0   
1          22.0     0.0  ...            1.0   
2          20.0     1.0  ...            1.0   
3          20.0     1.0  ...            0.0   
4          63.0     0.0  ...            0.0   

   White Blood cell count (thousand per microliter)  Blood test result  \
0                                          5.522560                2.0   
1                                          7.477132                2.0   
2                                          7.919321                1.0   
3                                         10.272230                2.0   
4                                          6.825974                2.0   

   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  \
0        1.0        1.0        1.0        1.0        0.0   
1        0.0        1.0        1.0        1.0        1.0   
2        0.0        0.0        1.0        0.0        0.0   
3        1.0        0.0        0.0        1.0        0.0   
4        0.0        0.0        0.0        0.0        0.0   

                               Genetic Disorder  Disorder Subclass  
0   Mitochondrial genetic inheritance disorders    Cystic fibrosis  
1  Multifactorial genetic inheritance disorders           Diabetes  
2   Mitochondrial genetic inheritance disorders     Leigh syndrome  
3              Single-gene inheritance diseases    Cystic fibrosis  
4              Single-gene inheritance diseases          Tay-Sachs  

[5 rows x 31 columns]

In [47]:
df = df.iloc[: , 1:]

In [48]:
df2 = df2.iloc[: , 1:]

In [49]:
df2['Disorder+Subclass'] = df2['Genetic Disorder'] + ' - ' + df2['Disorder Subclass']
df_train = df2.drop(["Genetic Disorder", "Disorder Subclass", "Disorder+Subclass"], axis=1)
df_test_Disorder = df2["Genetic Disorder"]
df_test_Subclass = df2["Disorder Subclass"]
df_test_Disorder_Subclass = df2["Disorder+Subclass"]


In [50]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_train_encoded = pd.DataFrame(scaler.fit_transform(df_train))

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

def compute_metrics(actual, predicted):
    #tn, fp, fn, tp = confusion_matrix(actual, predicted).ravel()
    print(confusion_matrix(actual, predicted))
    print("Accuracy: " + str(accuracy_score(actual, predicted)))
    print(classification_report(actual, predicted, zero_division=0))

In [76]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df_train_encoded, df_test_Disorder, test_size=0.30, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_train_encoded, df_test_Subclass, test_size=0.30, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(df_train_encoded, df_test_Disorder_Subclass, test_size=0.30, random_state=42)

In [68]:
pip install imblearn

     |████████████████████████████████| 199 kB 4.7 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [101]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_res, y_res = over_sampler.fit_resample(X_train1, y_train1)
y_res.value_counts()
X_res.describe()

0             1             2             3             4   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean       0.098444      0.071189      0.066213      0.063355      0.004881   
std        0.952772      0.988099      0.960173      0.980786      0.939820   
min       -1.196703     -0.792505     -1.235823     -0.863381     -3.418308   
25%       -1.196703     -0.792505     -1.235823     -0.863381     -0.619218   
50%        0.835629     -0.792505      0.809178     -0.863381      0.005741   
75%        0.835629      1.261822      0.809178      1.158237      0.641918   
max        0.835629      1.261822      0.809178      1.158237      3.468386   

                 5             6             7             8             9   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean       0.012351     -0.003856      0.017751     -0.004064      0.011195   
std        0.961977      0.964875      0.971451      0.972170      0.976059   
min       -1.357536     -1.080991     -0.995949     -0.897423     -0.890246   
25%       -0.849436     -1.013454     -0.995949     -0.897423     -0.890246   
50%       -0.282014     -0.163834      0.157345     -0.897423     -0.890246   
75%        0.857365      0.855353      1.004068      1.114301      1.123285   
max        1.995919      1.893472      1.004068      1.114301      1.123285   

       ...            17            18            19            20  \
count  ...  24537.000000  24537.000000  24537.000000  24537.000000   
mean   ...     -0.010732      0.006319      0.009943      0.009396   
std    ...      0.973173      0.952550      0.973830      0.962024   
min    ...     -1.117927     -1.494308     -1.104246     -1.779736   
25%    ...     -1.117927     -0.748052     -1.104246     -0.678521   
50%    ...      0.894513     -0.001796      0.905595     -0.002710   
75%    ...      0.894513      0.744460      0.905595      0.689923   
max    ...      0.894513      1.490715      0.905595      1.792468   

                 21            22            23            24            25  \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean      -0.015180      0.102138      0.140541      0.154428      0.177618   
std        0.961232      0.947273      0.942047      0.946469      0.985120   
min       -1.442417     -1.290832     -1.194605     -1.151004     -0.880998   
25%       -0.574114     -1.290832     -1.194605     -1.151004     -0.880998   
50%        0.294188      0.774694      0.837096      0.868807      0.928159   
75%        1.162491      0.774694      0.837096      0.868807      1.135077   
max        1.162491      0.774694      0.837096      0.868807      1.135077   

                 26  
count  24537.000000  
mean       0.186477  
std        0.998827  
min       -0.820002  
25%       -0.820002  
50%       -0.030294  
75%        1.219510  
max        1.219510  

[8 rows x 27 columns]

In [74]:
X_train1.describe()

0             1             2             3             4   \
count  14830.000000  14830.000000  14830.000000  14830.000000  14830.000000   
mean       0.001318      0.004845     -0.001928     -0.001161      0.003177   
std        0.999795      1.001158      1.000443      0.999862      0.997322   
min       -1.196703     -0.792505     -1.235823     -0.863381     -3.418308   
25%       -1.196703     -0.792505     -1.235823     -0.863381     -0.669919   
50%        0.835629     -0.792505      0.809178     -0.863381      0.002895   
75%        0.835629      1.261822      0.809178      1.158237      0.678525   
max        0.835629      1.261822      0.809178      1.158237      3.468386   

                 5             6             7             8             9   \
count  14830.000000  14830.000000  14830.000000  14830.000000  14830.000000   
mean       0.001738     -0.001798      0.004464      0.003851     -0.009207   
std        0.998641      1.000997      1.000042      1.000444      0.998918   
min       -1.357536     -1.080991     -0.995949     -0.897423     -0.890246   
25%       -0.849436     -1.080991     -0.995949     -0.897423     -0.890246   
50%       -0.341337     -0.202173      1.004068     -0.897423     -0.890246   
75%        0.878101      0.879451      1.004068      1.114301      1.123285   
max        1.995919      1.893472      1.004068      1.114301      1.123285   

       ...            17            18            19            20  \
count  ...  14830.000000  14830.000000  14830.000000  14830.000000   
mean   ...      0.004045      0.004796     -0.000527     -0.002076   
std    ...      0.999574      0.999173      1.000086      0.999656   
min    ...     -1.117927     -1.494308     -1.104246     -1.779736   
25%    ...     -1.117927     -0.748052     -1.104246     -0.723771   
50%    ...      0.894513     -0.001796      0.905595     -0.002710   
75%    ...      0.894513      0.744460      0.905595      0.708034   
max    ...      0.894513      1.490715      0.905595      1.792468   

                 21            22            23            24            25  \
count  14830.000000  14830.000000  14830.000000  14830.000000  14830.000000   
mean      -0.001725      0.002385      0.006606      0.001091     -0.000885   
std        0.998860      0.999415      0.998830      0.999879      0.999921   
min       -1.442417     -1.290832     -1.194605     -1.151004     -0.880998   
25%       -0.574114     -1.290832     -1.194605     -1.151004     -0.880998   
50%        0.294188      0.774694      0.837096      0.868807     -0.880998   
75%        1.162491      0.774694      0.837096      0.868807      1.135077   
max        1.162491      0.774694      0.837096      0.868807      1.135077   

                 26  
count  14830.000000  
mean      -0.001172  
std        0.999799  
min       -0.820002  
25%       -0.820002  
50%       -0.820002  
75%        1.219510  
max        1.219510  

[8 rows x 27 columns]

In [ ]:
X_test1

## Predicting Genetic Disorder

In [103]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_res, y_res = over_sampler.fit_resample(X_train1, y_train1)
y_res.value_counts()
X_res.describe()

0             1             2             3             4   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean       0.098444      0.071189      0.066213      0.063355      0.004881   
std        0.952772      0.988099      0.960173      0.980786      0.939820   
min       -1.196703     -0.792505     -1.235823     -0.863381     -3.418308   
25%       -1.196703     -0.792505     -1.235823     -0.863381     -0.619218   
50%        0.835629     -0.792505      0.809178     -0.863381      0.005741   
75%        0.835629      1.261822      0.809178      1.158237      0.641918   
max        0.835629      1.261822      0.809178      1.158237      3.468386   

                 5             6             7             8             9   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean       0.012351     -0.003856      0.017751     -0.004064      0.011195   
std        0.961977      0.964875      0.971451      0.972170      0.976059   
min       -1.357536     -1.080991     -0.995949     -0.897423     -0.890246   
25%       -0.849436     -1.013454     -0.995949     -0.897423     -0.890246   
50%       -0.282014     -0.163834      0.157345     -0.897423     -0.890246   
75%        0.857365      0.855353      1.004068      1.114301      1.123285   
max        1.995919      1.893472      1.004068      1.114301      1.123285   

       ...            17            18            19            20  \
count  ...  24537.000000  24537.000000  24537.000000  24537.000000   
mean   ...     -0.010732      0.006319      0.009943      0.009396   
std    ...      0.973173      0.952550      0.973830      0.962024   
min    ...     -1.117927     -1.494308     -1.104246     -1.779736   
25%    ...     -1.117927     -0.748052     -1.104246     -0.678521   
50%    ...      0.894513     -0.001796      0.905595     -0.002710   
75%    ...      0.894513      0.744460      0.905595      0.689923   
max    ...      0.894513      1.490715      0.905595      1.792468   

                 21            22            23            24            25  \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean      -0.015180      0.102138      0.140541      0.154428      0.177618   
std        0.961232      0.947273      0.942047      0.946469      0.985120   
min       -1.442417     -1.290832     -1.194605     -1.151004     -0.880998   
25%       -0.574114     -1.290832     -1.194605     -1.151004     -0.880998   
50%        0.294188      0.774694      0.837096      0.868807      0.928159   
75%        1.162491      0.774694      0.837096      0.868807      1.135077   
max        1.162491      0.774694      0.837096      0.868807      1.135077   

                 26  
count  24537.000000  
mean       0.186477  
std        0.998827  
min       -0.820002  
25%       -0.820002  
50%       -0.030294  
75%        1.219510  
max        1.219510  

[8 rows x 27 columns]

In [104]:
from sklearn.linear_model import LogisticRegression

logRegression = LogisticRegression()
logRegression.fit(X_res, y_res)
compute_metrics(y_test1, logRegression.predict(X_test1))

[[1557  385 1554]
 [  53  450   54]
 [ 855  624  824]]
Accuracy: 0.44540591567023285
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.45      0.52      3496
Multifactorial genetic inheritance disorders       0.31      0.81      0.45       557
            Single-gene inheritance diseases       0.34      0.36      0.35      2303

                                    accuracy                           0.45      6356
                                   macro avg       0.43      0.54      0.44      6356
                                weighted avg       0.50      0.45      0.45      6356



In [105]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_res, y_res)
compute_metrics(y_test1, decisionTree.predict(X_test1))

[[2099  228 1169]
 [ 153  210  194]
 [1069  260  974]]
Accuracy: 0.5165198237885462
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.60      0.62      3496
Multifactorial genetic inheritance disorders       0.30      0.38      0.33       557
            Single-gene inheritance diseases       0.42      0.42      0.42      2303

                                    accuracy                           0.52      6356
                                   macro avg       0.45      0.47      0.46      6356
                                weighted avg       0.53      0.52      0.52      6356



In [106]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(X_train1, y_train1)
compute_metrics(y_test1, randomForest.predict(X_test1))

[[3099   33  364]
 [ 237  113  207]
 [1605   69  629]]
Accuracy: 0.604310887350535
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.89      0.73      3496
Multifactorial genetic inheritance disorders       0.53      0.20      0.29       557
            Single-gene inheritance diseases       0.52      0.27      0.36      2303

                                    accuracy                           0.60      6356
                                   macro avg       0.56      0.45      0.46      6356
                                weighted avg       0.58      0.60      0.56      6356



In [107]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_train1, y_train1)
compute_metrics(y_test1, clf.predict(X_test1))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[2458   73  965]
 [ 142  160  255]
 [1072  167 1064]]
Accuracy: 0.579295154185022
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.67      0.70      0.69      3496
Multifactorial genetic inheritance disorders       0.40      0.29      0.33       557
            Single-gene inheritance diseases       0.47      0.46      0.46      2303

                                    accuracy                           0.58      6356
                                   macro avg       0.51      0.48      0.49      6356
                                weighted avg       0.57      0.58      0.57      6356



In [108]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train1, y_train1)
compute_metrics(y_test1, svc.predict(X_test1))

[[3181   35  280]
 [ 234  122  201]
 [1615   74  614]]
Accuracy: 0.6162680931403398
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.91      0.75      3496
Multifactorial genetic inheritance disorders       0.53      0.22      0.31       557
            Single-gene inheritance diseases       0.56      0.27      0.36      2303

                                    accuracy                           0.62      6356
                                   macro avg       0.57      0.47      0.47      6356
                                weighted avg       0.60      0.62      0.57      6356



## Predicting Subclass

In [109]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_train2, y_train2 = over_sampler.fit_resample(X_train2, y_train2)

In [110]:
logRegression = LogisticRegression()
logRegression.fit(X_train2, y_train2)
compute_metrics(y_test2, logRegression.predict(X_test2))

[[405 392   3 198  28   3]
 [152 359   2  40   4   2]
 [  2   0 271  11  36 100]
 [386 171 170 719 469 234]
 [ 89  22 204 375 352 282]
 [  9   0 320 108 189 249]]
Accuracy: 0.37051604782882314
                        precision    recall  f1-score   support

       Cystic fibrosis       0.39      0.39      0.39      1029
              Diabetes       0.38      0.64      0.48       559
       Hemochromatosis       0.28      0.65      0.39       420
        Leigh syndrome       0.50      0.33      0.40      2149
Mitochondrial myopathy       0.33      0.27      0.29      1324
             Tay-Sachs       0.29      0.28      0.29       875

              accuracy                           0.37      6356
             macro avg       0.36      0.43      0.37      6356
          weighted avg       0.39      0.37      0.37      6356



In [111]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train2, y_train2)
compute_metrics(y_test2, decisionTree.predict(X_test2))

[[343 200   6 355  95  30]
 [201 149   4 158  39   8]
 [  9   2  88 107 109 105]
 [337 149  84 838 489 252]
 [118  42  94 445 388 237]
 [ 28  10 121 246 260 210]]
Accuracy: 0.31718061674008813
                        precision    recall  f1-score   support

       Cystic fibrosis       0.33      0.33      0.33      1029
              Diabetes       0.27      0.27      0.27       559
       Hemochromatosis       0.22      0.21      0.22       420
        Leigh syndrome       0.39      0.39      0.39      2149
Mitochondrial myopathy       0.28      0.29      0.29      1324
             Tay-Sachs       0.25      0.24      0.24       875

              accuracy                           0.32      6356
             macro avg       0.29      0.29      0.29      6356
          weighted avg       0.32      0.32      0.32      6356



In [112]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train2, y_train2)
compute_metrics(y_test2, randomForest.predict(X_test2))

[[ 465  150    0  373   36    5]
 [ 276  171    1  101    7    3]
 [   1    0   94   78   86  161]
 [ 323   72   40 1171  374  169]
 [  58    6   71  676  330  183]
 [  10    1  106  277  243  238]]
Accuracy: 0.38845185651353054
                        precision    recall  f1-score   support

       Cystic fibrosis       0.41      0.45      0.43      1029
              Diabetes       0.43      0.31      0.36       559
       Hemochromatosis       0.30      0.22      0.26       420
        Leigh syndrome       0.44      0.54      0.49      2149
Mitochondrial myopathy       0.31      0.25      0.28      1324
             Tay-Sachs       0.31      0.27      0.29       875

              accuracy                           0.39      6356
             macro avg       0.37      0.34      0.35      6356
          weighted avg       0.38      0.39      0.38      6356



In [113]:
mlp = MLPClassifier()
mlp.fit(X_train2, y_train2)
compute_metrics(y_test2, mlp.predict(X_test2))

[[492 299   6 156  61  15]
 [272 234   1  33  12   7]
 [  2   1 153   8  70 186]
 [429 214 160 446 522 378]
 [104  55 182 209 417 357]
 [ 13   6 226  76 213 341]]
Accuracy: 0.3277218376337319
                        precision    recall  f1-score   support

       Cystic fibrosis       0.38      0.48      0.42      1029
              Diabetes       0.29      0.42      0.34       559
       Hemochromatosis       0.21      0.36      0.27       420
        Leigh syndrome       0.48      0.21      0.29      2149
Mitochondrial myopathy       0.32      0.31      0.32      1324
             Tay-Sachs       0.27      0.39      0.32       875

              accuracy                           0.33      6356
             macro avg       0.32      0.36      0.33      6356
          weighted avg       0.37      0.33      0.32      6356



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [114]:
svc = SVC()
svc.fit(X_train2, y_train2)
compute_metrics(y_test2, svc.predict(X_test2))

[[471 281   3 219  46   9]
 [239 259   1  48  10   2]
 [  1   0 169  24  66 160]
 [394 157 123 734 491 250]
 [ 95  30 139 400 385 275]
 [ 14   3 230 130 202 296]]
Accuracy: 0.3640654499685337
                        precision    recall  f1-score   support

       Cystic fibrosis       0.39      0.46      0.42      1029
              Diabetes       0.35      0.46      0.40       559
       Hemochromatosis       0.25      0.40      0.31       420
        Leigh syndrome       0.47      0.34      0.40      2149
Mitochondrial myopathy       0.32      0.29      0.31      1324
             Tay-Sachs       0.30      0.34      0.32       875

              accuracy                           0.36      6356
             macro avg       0.35      0.38      0.36      6356
          weighted avg       0.38      0.36      0.37      6356



# Predicting Disorder + Subclass

In [63]:
logRegression = LogisticRegression()
logRegression.fit(X_train3, y_train3)
compute_metrics(y_test3, logRegression.predict(X_test3))

[[   0    0    0   38    1    0    6    0   41    0    0    1]
 [   0    0    0   11    0    0   12    0   30    0    0    0]
 [   0    0    0    6    7    0    0    0    0   12    0   15]
 [   0    0    0 1352  252    0   19    0  180   13    0   81]
 [   0    0    0  754  366    0    2    0   35   37    0  130]
 [   0    0    0   38   21    0    0    0    0    7    0   29]
 [   0    0    0  100    2    0  119    0  283    0    0    2]
 [   0    0    0   14    0    0   12    0   24    0    0    1]
 [   0    0    0  401    7    0   75    0  458    0    0    1]
 [   0    0    0   42  100    0    0    0    0   82    0  156]
 [   0    0    0   78   36    0    8    0   35   18    0   26]
 [   0    0    0  256  250    0    0    0    2   56    0  216]]
Accuracy: 0.407960981749528
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.00      0.00      0.00     

In [64]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train3, y_train3)
compute_metrics(y_test3, decisionTree.predict(X_test3))

[[  5   0   0  22  11   0  18   4  17   0   5   5]
 [  1   2   0   7   5   1  13   1  18   0   3   2]
 [  0   0   2  10  12   2   0   0   1   6   0   7]
 [ 30   9  11 634 422  33 111  11 264  73  90 209]
 [ 17   6  16 448 353  23  29   3  98  74  55 202]
 [  0   1   3  24  28   2   0   0   5  11   2  19]
 [ 16  17   0  94  35   1 138  16 163   1  21   4]
 [  4   1   0   5   4   0  15   0  19   1   2   0]
 [ 22  18   3 251  90   3 188  19 278   4  38  28]
 [  0   0   7  85  78   8   0   3   5  77  19  98]
 [  6   1   0  56  42   4  17   1  31  14   2  27]
 [  5   2  12 190 202  14  12   1  24 103  36 179]]
Accuracy: 0.263058527375708
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.05      0.06      0.05        87
              Mitochondrial genetic inheritance disorders - Diabetes       0.04      0.04      0.04        53
       Mitochondrial genetic

In [65]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train3, y_train3)
compute_metrics(y_test3, randomForest.predict(X_test3))

[[   0    0    0   50    3    0    5    0   28    0    0    1]
 [   0    0    0   15    0    0   12    0   26    0    0    0]
 [   0    0    0   10    8    0    0    0    0    9    0   13]
 [   0    0    0 1292  325    0   22    0  178   10    0   70]
 [   0    0    0  794  354    0    4    0   35   29    0  108]
 [   0    0    0   49   27    0    0    0    0    4    0   15]
 [   0    1    0  126    8    0  122    0  248    1    0    0]
 [   0    0    0   10    1    0   11    0   28    0    0    1]
 [   0    0    0  441   23    0  106    0  370    0    0    2]
 [   0    0    0  105  109    0    0    0    0   56    0  110]
 [   0    0    0   90   44    0    7    0   30    8    0   22]
 [   0    0    1  323  274    0    0    0    3   45    1  133]]
Accuracy: 0.3661107614852108
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.00      0.00      0.00    

In [66]:
mlp = MLPClassifier()
mlp.fit(X_train3, y_train3)
compute_metrics(y_test3, mlp.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[   1    1    0   30    6    0   11    0   37    0    0    1]
 [   0    0    0   11    0    0   14    0   28    0    0    0]
 [   0    0    0    3   14    0    0    0    1   11    2    9]
 [   1    1    1 1062  406    1   41    3  222   39    2  118]
 [   1    0    3  650  357    4    8    0   43   69    4  185]
 [   0    0    0   31   24    0    0    0    0   15    0   25]
 [   1    3    0   94   12    0  156    5  234    0    0    1]
 [   0    2    0   14    1    0   13    1   19    0    0    1]
 [   0    0    0  350   36    0  148    4  403    0    1    0]
 [   0    0    1   66   82    1    0    0    0  109    4  117]
 [   0    1    0   61   45    0   11    3   33   18    1   28]
 [   0    0    1  226  233    2    0    0    7  111    3  197]]
Accuracy: 0.35981749528005036
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.25      0.01      0.02   

In [67]:
svc = SVC()
svc.fit(X_train3, y_train3)
compute_metrics(y_test3, svc.predict(X_test3))

[[   0    0    0   43    2    0    3    0   39    0    0    0]
 [   0    0    0   11    0    0    8    0   34    0    0    0]
 [   0    0    0    6   12    0    0    0    0    6    0   16]
 [   0    0    0 1288  322    0   18    0  196   10    0   63]
 [   0    0    0  764  369    0    3    0   38   22    0  128]
 [   0    0    0   43   25    0    0    0    0    6    0   21]
 [   0    0    0  103    6    0  104    0  292    0    0    1]
 [   0    0    0   11    1    0   13    0   25    0    0    1]
 [   0    0    0  400   13    0   71    0  458    0    0    0]
 [   0    0    0   70  116    0    0    0    0   60    0  134]
 [   0    0    0   89   37    0    4    0   38   11    0   22]
 [   0    0    0  278  269    0    0    0    3   39    0  191]]
Accuracy: 0.3886091881686595
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.00      0.00      0.00    