In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [12]:
#df = pd.read_csv("train_processed.csv")
df2 = pd.read_csv("train_processed_encoded_balanced.csv")
balanced_x = pd.read_csv("x_resampled.csv")
balanced_y = pd.read_csv("y_resampled.csv")

In [13]:
balanced_x.head()

Unnamed: 0  Patient Age  Genes in mother's side  Inherited from father  \
0           0          4.0                     1.0                    1.0   
1           1          2.0                     1.0                    1.0   
2           2          3.0                     1.0                    0.0   
3           3          4.0                     1.0                    0.0   
4           4          6.0                     1.0                    0.0   

   Maternal gene  Paternal gene  Blood cell count (mcL)  Mother's age  \
0            0.0            0.0                4.910669           5.0   
1            1.0            1.0                4.927532          22.0   
2            1.0            1.0                5.125172           5.0   
3            1.0            1.0                4.968662          21.0   
4            1.0            0.0                4.769206           9.0   

   Father's age  Status  ...  History of anomalies in previous pregnancies  \
0          23.0     1.0  ...                                           1.0   
1          49.0     1.0  ...                                           1.0   
2          51.0     0.0  ...                                           0.0   
3          20.0     1.0  ...                                           1.0   
4          21.0     1.0  ...                                           1.0   

   No. of previous abortion  Birth defects  \
0                       2.0            0.0   
1                       2.0            1.0   
2                       2.0            1.0   
3                       2.0            0.0   
4                       0.0            1.0   

   White Blood cell count (thousand per microliter)  Blood test result  \
0                                          5.522560                2.0   
1                                          5.169576                0.0   
2                                          5.398418                3.0   
3                                          5.648993                0.0   
4                                          8.585701                2.0   

   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  
0        1.0        1.0        1.0        1.0        0.0  
1        1.0        1.0        0.0        0.0        1.0  
2        1.0        0.0        1.0        0.0        1.0  
3        1.0        0.0        1.0        0.0        1.0  
4        1.0        0.0        0.0        1.0        1.0  

[5 rows x 34 columns]

In [40]:
df2.head()

Unnamed: 0  Patient Age  Genes in mother's side  Inherited from father  \
0           1          4.0                     1.0                    1.0   
1           2          6.0                     1.0                    0.0   
2           3         12.0                     1.0                    0.0   
3           5         14.0                     1.0                    0.0   
4           6          3.0                     1.0                    0.0   

   Maternal gene  Paternal gene  Blood cell count (mcL)  Mother's age  \
0            0.0            0.0                4.910669           5.0   
1            0.0            0.0                4.893297          23.0   
2            1.0            0.0                4.705280           3.0   
3            1.0            0.0                5.103188           5.0   
4            1.0            1.0                4.901080           5.0   

   Father's age  Status  ...  Birth defects  \
0          23.0     1.0  ...            0.0   
1          22.0     0.0  ...            1.0   
2          20.0     1.0  ...            1.0   
3          20.0     1.0  ...            0.0   
4          63.0     0.0  ...            0.0   

   White Blood cell count (thousand per microliter)  Blood test result  \
0                                          5.522560                2.0   
1                                          7.477132                2.0   
2                                          7.919321                1.0   
3                                         10.272230                2.0   
4                                          6.825974                2.0   

   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  \
0        1.0        1.0        1.0        1.0        0.0   
1        0.0        1.0        1.0        1.0        1.0   
2        0.0        0.0        1.0        0.0        0.0   
3        1.0        0.0        0.0        1.0        0.0   
4        0.0        0.0        0.0        0.0        0.0   

                               Genetic Disorder  Disorder Subclass  
0   Mitochondrial genetic inheritance disorders    Cystic fibrosis  
1  Multifactorial genetic inheritance disorders           Diabetes  
2   Mitochondrial genetic inheritance disorders     Leigh syndrome  
3              Single-gene inheritance diseases    Cystic fibrosis  
4              Single-gene inheritance diseases          Tay-Sachs  

[5 rows x 31 columns]

In [47]:
df = df.iloc[: , 1:]

In [48]:
df2 = df2.iloc[: , 1:]

In [14]:
balanced_x = balanced_x.iloc[:, 1:]
balanced_y = balanced_y.iloc[:, 1:]

In [15]:
balanced_y.head()

Combined
0  Mitochondrial genetic inheritance disorders - ...
1  Mitochondrial genetic inheritance disorders - ...
2  Mitochondrial genetic inheritance disorders - ...
3  Mitochondrial genetic inheritance disorders - ...
4  Mitochondrial genetic inheritance disorders - ...

In [16]:
df2['Disorder+Subclass'] = df2['Genetic Disorder'] + ' - ' + df2['Disorder Subclass']
df_train = df2.drop(["Genetic Disorder", "Disorder Subclass", "Disorder+Subclass"], axis=1)
df_test_Disorder = df2["Genetic Disorder"]
df_test_Subclass = df2["Disorder Subclass"]
df_test_Disorder_Subclass = df2["Disorder+Subclass"]


In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_train_encoded = pd.DataFrame(scaler.fit_transform(df_train))

In [20]:
scaler2 = StandardScaler()
df_balanced_encoded = pd.DataFrame(scaler2.fit_transform(balanced_x))

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

def compute_metrics(actual, predicted):
    #tn, fp, fn, tp = confusion_matrix(actual, predicted).ravel()
    print(confusion_matrix(actual, predicted))
    print("Accuracy: " + str(accuracy_score(actual, predicted)))
    print(classification_report(actual, predicted, zero_division=0))

In [28]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df_train_encoded, df_test_Disorder, test_size=0.30, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_train_encoded, df_test_Subclass, test_size=0.30, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(df_balanced_encoded, balanced_y, test_size=0.30, random_state=42)

In [29]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_res, y_res = over_sampler.fit_resample(X_train1, y_train1)
y_res.value_counts()
X_res.describe()

0             1             2             3             4   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean      -0.007523     -0.010921      0.098651      0.070892      0.070396   
std        0.952726      0.955754      0.952573      0.988343      0.957729   
min       -1.732362     -1.600769     -1.196703     -0.792505     -1.235823   
25%       -0.813665     -0.730456     -1.196703     -0.792505     -1.235823   
50%       -0.010943     -0.128855      0.835629     -0.792505      0.809178   
75%        0.796950      0.757753      0.835629      1.261822      0.809178   
max        1.732760      1.701161      0.835629      1.261822      0.809178   

                 5             6             7             8             9   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean       0.063224      0.006058      0.009186     -0.003024      0.021405   
std        0.980915      0.937577      0.959552      0.964589      0.971190   
min       -0.863381     -3.418308     -1.357536     -1.080991     -0.995949   
25%       -0.863381     -0.617009     -0.849436     -1.013390     -0.995949   
50%       -0.863381      0.000224     -0.277798     -0.164930      0.192770   
75%        1.158237      0.639361      0.818972      0.848925      1.004068   
max        1.158237      3.468386      1.995919      1.893472      1.004068   

       ...            19            20            21            22  \
count  ...  24537.000000  24537.000000  24537.000000  24537.000000   
mean   ...     -0.013238      0.005350      0.010063      0.008244   
std    ...      0.973170      0.951768      0.970655      0.959487   
min    ...     -1.117927     -1.494308     -1.104246     -1.779736   
25%    ...     -1.117927     -0.748052     -1.104246     -0.671063   
50%    ...      0.894513     -0.001796      0.905595     -0.002710   
75%    ...      0.894513      0.744460      0.905595      0.684852   
max    ...      0.894513      1.490715      0.905595      1.792468   

                 23            24            25            26            27  \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean      -0.016426      0.098886      0.140286      0.156672      0.178326   
std        0.961778      0.946327      0.940611      0.943353      0.983728   
min       -1.442417     -1.290832     -1.194605     -1.151004     -0.880998   
25%       -0.574114     -1.290832     -1.194605     -1.151004     -0.880998   
50%        0.294188      0.774694      0.837096      0.868807      0.892827   
75%        1.162491      0.774694      0.837096      0.868807      1.135077   
max        1.162491      0.774694      0.837096      0.868807      1.135077   

                 28  
count  24537.000000  
mean       0.184897  
std        0.997759  
min       -0.820002  
25%       -0.820002  
50%       -0.020029  
75%        1.219510  
max        1.219510  

[8 rows x 29 columns]

In [30]:
X_train1.describe()

0             1             2             3             4   \
count  14830.000000  14830.000000  14830.000000  14830.000000  14830.000000   
mean       0.000863     -0.002222      0.001318      0.004845     -0.001928   
std        1.002269      0.997443      0.999795      1.001158      1.000443   
min       -1.732362     -1.600769     -1.196703     -0.792505     -1.235823   
25%       -0.870554     -0.657360     -1.196703     -0.792505     -1.235823   
50%        0.007497     -0.185656      0.835629     -0.792505      0.809178   
75%        0.873502      0.757753      0.835629      1.261822      0.809178   
max        1.732760      1.701161      0.835629      1.261822      0.809178   

                 5             6             7             8             9   \
count  14830.000000  14830.000000  14830.000000  14830.000000  14830.000000   
mean      -0.001161      0.003177      0.001738     -0.001798      0.004464   
std        0.999862      0.997322      0.998641      1.000997      1.000042   
min       -0.863381     -3.418308     -1.357536     -1.080991     -0.995949   
25%       -0.863381     -0.669919     -0.849436     -1.080991     -0.995949   
50%       -0.863381      0.002895     -0.341337     -0.202173      1.004068   
75%        1.158237      0.678525      0.878101      0.879451      1.004068   
max        1.158237      3.468386      1.995919      1.893472      1.004068   

       ...            19            20            21            22  \
count  ...  14830.000000  14830.000000  14830.000000  14830.000000   
mean   ...      0.004045      0.004796     -0.000527     -0.002076   
std    ...      0.999574      0.999173      1.000086      0.999656   
min    ...     -1.117927     -1.494308     -1.104246     -1.779736   
25%    ...     -1.117927     -0.748052     -1.104246     -0.723771   
50%    ...      0.894513     -0.001796      0.905595     -0.002710   
75%    ...      0.894513      0.744460      0.905595      0.708034   
max    ...      0.894513      1.490715      0.905595      1.792468   

                 23            24            25            26            27  \
count  14830.000000  14830.000000  14830.000000  14830.000000  14830.000000   
mean      -0.001725      0.002385      0.006606      0.001091     -0.000885   
std        0.998860      0.999415      0.998830      0.999879      0.999921   
min       -1.442417     -1.290832     -1.194605     -1.151004     -0.880998   
25%       -0.574114     -1.290832     -1.194605     -1.151004     -0.880998   
50%        0.294188      0.774694      0.837096      0.868807     -0.880998   
75%        1.162491      0.774694      0.837096      0.868807      1.135077   
max        1.162491      0.774694      0.837096      0.868807      1.135077   

                 28  
count  14830.000000  
mean      -0.001172  
std        0.999799  
min       -0.820002  
25%       -0.820002  
50%       -0.820002  
75%        1.219510  
max        1.219510  

[8 rows x 29 columns]

In [31]:
X_test1

0         1         2         3         4         5         6   \
3912  -1.093480  1.229457 -1.196703 -0.792505 -1.235823  1.158237  0.088451   
6216  -0.715267 -0.185656  0.835629 -0.792505 -1.235823 -0.863381  1.229022   
8158  -0.397317 -0.893212  0.835629 -0.792505  0.809178 -0.863381  0.429377   
13020  0.396774  0.521901 -1.196703  1.261822 -1.235823 -0.863381  1.190580   
4639  -0.974837  0.521901 -1.196703 -0.792505  0.809178 -0.863381 -0.831998   
...         ...       ...       ...       ...       ...       ...       ...   
1281  -1.523011  0.050196 -1.196703 -0.792505 -1.235823  1.158237 -0.166893   
2566  -1.313346 -1.364917  0.835629 -0.792505 -1.235823 -0.863381  0.502599   
8993  -0.259999 -0.185656  0.835629 -0.792505 -1.235823 -0.863381  1.684485   
15174  0.748778 -0.893212 -1.196703 -0.792505  0.809178  1.158237  0.774107   
10010 -0.093020  0.286048  0.835629  1.261822  0.809178 -0.863381 -0.139417   

             7         8         9   ...        19        20        21  \
3912  -0.442957  1.893472 -0.995949  ...  0.894513 -1.494308 -1.104246   
6216   1.589439  1.014653 -0.995949  ...  0.894513 -0.748052  0.905595   
8158  -0.849436 -1.080991  1.004068  ... -1.117927 -0.748052  0.905595   
13020 -1.154296 -0.337375 -0.995949  ... -1.117927 -1.494308  0.905595   
4639  -0.442957  0.406240  1.004068  ...  0.894513  1.490715 -1.104246   
...         ...       ...       ...  ...       ...       ...       ...   
1281   0.471621  0.473842 -0.995949  ...  0.894513 -0.001796 -1.104246   
2566  -0.747817  0.744248  1.004068  ...  0.894513  0.744460  0.905595   
8993   0.471621 -1.080991  1.004068  ... -1.117927 -0.001796  0.905595   
15174 -0.849436 -0.540180 -0.995949  ...  0.894513 -1.494308  0.905595   
10010  0.776481  1.014653 -0.995949  ... -1.117927 -0.748052  0.905595   

             22        23        24        25        26        27        28  
3912  -0.889558 -1.442417  0.774694  0.837096 -1.151004 -0.880998 -0.820002  
6216  -0.120039 -0.574114  0.774694 -1.194605  0.868807 -0.880998  1.219510  
8158  -0.002710 -1.442417 -1.290832  0.837096  0.868807  1.135077  1.219510  
13020  0.119321 -1.442417  0.774694  0.837096  0.868807 -0.880998 -0.820002  
4639   1.217439 -0.574114  0.774694 -1.194605 -1.151004 -0.880998 -0.820002  
...         ...       ...       ...       ...       ...       ...       ...  
1281  -1.617844  1.162491  0.774694 -1.194605  0.868807  1.135077  1.219510  
2566   0.100962  0.294188 -1.290832 -1.194605  0.868807 -0.880998 -0.820002  
8993   0.825597  1.162491 -1.290832 -1.194605  0.868807  1.135077 -0.820002  
15174 -0.200175  1.162491 -1.290832  0.837096  0.868807 -0.880998  1.219510  
10010 -0.107256 -1.442417  0.774694  0.837096  0.868807  1.135077 -0.820002  

[6356 rows x 29 columns]

## Predicting Genetic Disorder

In [32]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_res, y_res = over_sampler.fit_resample(X_train1, y_train1)
y_res.value_counts()
X_res.describe()

0             1             2             3             4   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean      -0.007523     -0.010921      0.098651      0.070892      0.070396   
std        0.952726      0.955754      0.952573      0.988343      0.957729   
min       -1.732362     -1.600769     -1.196703     -0.792505     -1.235823   
25%       -0.813665     -0.730456     -1.196703     -0.792505     -1.235823   
50%       -0.010943     -0.128855      0.835629     -0.792505      0.809178   
75%        0.796950      0.757753      0.835629      1.261822      0.809178   
max        1.732760      1.701161      0.835629      1.261822      0.809178   

                 5             6             7             8             9   \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean       0.063224      0.006058      0.009186     -0.003024      0.021405   
std        0.980915      0.937577      0.959552      0.964589      0.971190   
min       -0.863381     -3.418308     -1.357536     -1.080991     -0.995949   
25%       -0.863381     -0.617009     -0.849436     -1.013390     -0.995949   
50%       -0.863381      0.000224     -0.277798     -0.164930      0.192770   
75%        1.158237      0.639361      0.818972      0.848925      1.004068   
max        1.158237      3.468386      1.995919      1.893472      1.004068   

       ...            19            20            21            22  \
count  ...  24537.000000  24537.000000  24537.000000  24537.000000   
mean   ...     -0.013238      0.005350      0.010063      0.008244   
std    ...      0.973170      0.951768      0.970655      0.959487   
min    ...     -1.117927     -1.494308     -1.104246     -1.779736   
25%    ...     -1.117927     -0.748052     -1.104246     -0.671063   
50%    ...      0.894513     -0.001796      0.905595     -0.002710   
75%    ...      0.894513      0.744460      0.905595      0.684852   
max    ...      0.894513      1.490715      0.905595      1.792468   

                 23            24            25            26            27  \
count  24537.000000  24537.000000  24537.000000  24537.000000  24537.000000   
mean      -0.016426      0.098886      0.140286      0.156672      0.178326   
std        0.961778      0.946327      0.940611      0.943353      0.983728   
min       -1.442417     -1.290832     -1.194605     -1.151004     -0.880998   
25%       -0.574114     -1.290832     -1.194605     -1.151004     -0.880998   
50%        0.294188      0.774694      0.837096      0.868807      0.892827   
75%        1.162491      0.774694      0.837096      0.868807      1.135077   
max        1.162491      0.774694      0.837096      0.868807      1.135077   

                 28  
count  24537.000000  
mean       0.184897  
std        0.997759  
min       -0.820002  
25%       -0.820002  
50%       -0.020029  
75%        1.219510  
max        1.219510  

[8 rows x 29 columns]

In [33]:
from sklearn.linear_model import LogisticRegression

logRegression = LogisticRegression()
logRegression.fit(X_res, y_res)
compute_metrics(y_test1, logRegression.predict(X_test1))

[[1558  384 1554]
 [  51  446   60]
 [ 832  619  852]]
Accuracy: 0.44933920704845814
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.64      0.45      0.52      3496
Multifactorial genetic inheritance disorders       0.31      0.80      0.44       557
            Single-gene inheritance diseases       0.35      0.37      0.36      2303

                                    accuracy                           0.45      6356
                                   macro avg       0.43      0.54      0.44      6356
                                weighted avg       0.50      0.45      0.46      6356



In [34]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_res, y_res)
compute_metrics(y_test1, decisionTree.predict(X_test1))

[[2124  206 1166]
 [ 162  198  197]
 [1060  231 1012]]
Accuracy: 0.5245437382001259
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.61      0.62      3496
Multifactorial genetic inheritance disorders       0.31      0.36      0.33       557
            Single-gene inheritance diseases       0.43      0.44      0.43      2303

                                    accuracy                           0.52      6356
                                   macro avg       0.46      0.47      0.46      6356
                                weighted avg       0.53      0.52      0.53      6356



In [35]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(X_train1, y_train1)
compute_metrics(y_test1, randomForest.predict(X_test1))

[[3141   28  327]
 [ 264  112  181]
 [1651   46  606]]
Accuracy: 0.6071428571428571
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.62      0.90      0.73      3496
Multifactorial genetic inheritance disorders       0.60      0.20      0.30       557
            Single-gene inheritance diseases       0.54      0.26      0.35      2303

                                    accuracy                           0.61      6356
                                   macro avg       0.59      0.45      0.46      6356
                                weighted avg       0.59      0.61      0.56      6356



In [36]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_train1, y_train1)
compute_metrics(y_test1, clf.predict(X_test1))

[[2498   89  909]
 [ 140  174  243]
 [1138  166  999]]
Accuracy: 0.5775645059786029
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.66      0.71      0.69      3496
Multifactorial genetic inheritance disorders       0.41      0.31      0.35       557
            Single-gene inheritance diseases       0.46      0.43      0.45      2303

                                    accuracy                           0.58      6356
                                   macro avg       0.51      0.49      0.50      6356
                                weighted avg       0.57      0.58      0.57      6356



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [37]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train1, y_train1)
compute_metrics(y_test1, svc.predict(X_test1))

[[3179   30  287]
 [ 243  128  186]
 [1642   69  592]]
Accuracy: 0.6134361233480177
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.91      0.74      3496
Multifactorial genetic inheritance disorders       0.56      0.23      0.33       557
            Single-gene inheritance diseases       0.56      0.26      0.35      2303

                                    accuracy                           0.61      6356
                                   macro avg       0.58      0.47      0.47      6356
                                weighted avg       0.60      0.61      0.56      6356



## Predicting Subclass

In [38]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(random_state=42)
X_train2, y_train2 = over_sampler.fit_resample(X_train2, y_train2)

In [39]:
logRegression = LogisticRegression()
logRegression.fit(X_train2, y_train2)
compute_metrics(y_test2, logRegression.predict(X_test2))

[[429 363   2 199  31   5]
 [168 342   2  40   5   2]
 [  1   0 258  16  37 108]
 [386 156 154 739 480 234]
 [ 83  19 194 383 367 278]
 [  9   0 299  98 214 255]]
Accuracy: 0.3760226557583386
                        precision    recall  f1-score   support

       Cystic fibrosis       0.40      0.42      0.41      1029
              Diabetes       0.39      0.61      0.48       559
       Hemochromatosis       0.28      0.61      0.39       420
        Leigh syndrome       0.50      0.34      0.41      2149
Mitochondrial myopathy       0.32      0.28      0.30      1324
             Tay-Sachs       0.29      0.29      0.29       875

              accuracy                           0.38      6356
             macro avg       0.36      0.43      0.38      6356
          weighted avg       0.39      0.38      0.37      6356



In [40]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train2, y_train2)
compute_metrics(y_test2, decisionTree.predict(X_test2))

[[356 257   8 302  85  21]
 [210 187   3 122  33   4]
 [ 10   2 101  86  92 129]
 [337 148 100 819 462 283]
 [124  45 110 433 369 243]
 [ 33   7 140 214 239 242]]
Accuracy: 0.3263058527375708
                        precision    recall  f1-score   support

       Cystic fibrosis       0.33      0.35      0.34      1029
              Diabetes       0.29      0.33      0.31       559
       Hemochromatosis       0.22      0.24      0.23       420
        Leigh syndrome       0.41      0.38      0.40      2149
Mitochondrial myopathy       0.29      0.28      0.28      1324
             Tay-Sachs       0.26      0.28      0.27       875

              accuracy                           0.33      6356
             macro avg       0.30      0.31      0.30      6356
          weighted avg       0.33      0.33      0.33      6356



In [41]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train2, y_train2)
compute_metrics(y_test2, randomForest.predict(X_test2))

[[ 449  143    0  408   26    3]
 [ 257  178    1  114    8    1]
 [   1    0  113   83   80  143]
 [ 289   70   43 1221  351  175]
 [  49    6   60  682  324  203]
 [   3    0  100  291  230  251]]
Accuracy: 0.3989930774071743
                        precision    recall  f1-score   support

       Cystic fibrosis       0.43      0.44      0.43      1029
              Diabetes       0.45      0.32      0.37       559
       Hemochromatosis       0.36      0.27      0.31       420
        Leigh syndrome       0.44      0.57      0.49      2149
Mitochondrial myopathy       0.32      0.24      0.28      1324
             Tay-Sachs       0.32      0.29      0.30       875

              accuracy                           0.40      6356
             macro avg       0.39      0.35      0.36      6356
          weighted avg       0.39      0.40      0.39      6356



In [42]:
mlp = MLPClassifier()
mlp.fit(X_train2, y_train2)
compute_metrics(y_test2, mlp.predict(X_test2))

[[480 229   4 245  56  15]
 [241 235   1  70   9   3]
 [  1   0 153  45  78 143]
 [407 148 121 657 544 272]
 [ 92  35 139 350 415 293]
 [ 12   4 201 149 224 285]]
Accuracy: 0.35006293266205163
                        precision    recall  f1-score   support

       Cystic fibrosis       0.39      0.47      0.42      1029
              Diabetes       0.36      0.42      0.39       559
       Hemochromatosis       0.25      0.36      0.29       420
        Leigh syndrome       0.43      0.31      0.36      2149
Mitochondrial myopathy       0.31      0.31      0.31      1324
             Tay-Sachs       0.28      0.33      0.30       875

              accuracy                           0.35      6356
             macro avg       0.34      0.37      0.35      6356
          weighted avg       0.36      0.35      0.35      6356



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [43]:
svc = SVC()
svc.fit(X_train2, y_train2)
compute_metrics(y_test2, svc.predict(X_test2))

[[ 411  219    1  357   35    6]
 [ 216  231    0  104    3    5]
 [   1    0  145   58   75  141]
 [ 313  100   79 1077  408  172]
 [  63   18  110  584  339  210]
 [  10    0  167  281  176  241]]
Accuracy: 0.38451856513530525
                        precision    recall  f1-score   support

       Cystic fibrosis       0.41      0.40      0.40      1029
              Diabetes       0.41      0.41      0.41       559
       Hemochromatosis       0.29      0.35      0.31       420
        Leigh syndrome       0.44      0.50      0.47      2149
Mitochondrial myopathy       0.33      0.26      0.29      1324
             Tay-Sachs       0.31      0.28      0.29       875

              accuracy                           0.38      6356
             macro avg       0.36      0.37      0.36      6356
          weighted avg       0.38      0.38      0.38      6356



# Predicting Disorder + Subclass

In [44]:
logRegression = LogisticRegression()
logRegression.fit(X_train3, y_train3)
compute_metrics(y_test3, logRegression.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[128  34  20  21   7  80  75   0  52   1]
 [ 36 290   2   0   1  62  22   0   4   0]
 [ 56   5  78  88  47  15  38  12  71  33]
 [ 15   1  54  74  64   6  12  43  73  62]
 [  6   0  15  57 157   0   0 101  32  66]
 [ 55 134  22   8   1 118  62   0   8   1]
 [113  56  36  14   3  81  91   2  38   4]
 [  0   0   6  20  79   0   2 229   6  76]
 [ 55  22  37  30  61  26  24  62  58  40]
 [  5   0  24  64  78   1   1 111  32  88]]
Accuracy: 0.31214285714285717
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.27      0.31      0.29       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.54      0.70      0.60       417
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.27      0.18      0.21       443
             Mitochondrial genetic inheritance

In [45]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train3, y_train3)
compute_metrics(y_test3, decisionTree.predict(X_test3))

[[228  60  11  11  12  24  21   6  39   6]
 [ 57 223   7   7   1  69  40   2  11   0]
 [ 24   5  91  91  13  34  58  35  32  60]
 [  9   4  52  94  22  24  25  49  40  85]
 [ 12   1  15  17 266   3   3  30  57  30]
 [ 25  61  33  29   2 136  92   3  23   5]
 [ 24  34  61  33   4 117 110   7  33  15]
 [  2   0  39  53  34   3   5 137  50  95]
 [ 51  18  29  36  58  24  35  39  93  32]
 [  7   0  49  83  25   8  18  85  29 100]]
Accuracy: 0.3519047619047619
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.52      0.55      0.53       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.55      0.53      0.54       417
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.24      0.21      0.22       443
             Mitochondrial genetic inheritance 

In [46]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train3, y_train3)
compute_metrics(y_test3, randomForest.predict(X_test3))

<ipython-input-46-fcefb1d5c135>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomForest.fit(X_train3, y_train3)


[[312  14  22  12   5  35  11   1   0   6]
 [ 19 248   9   1   0 104  34   0   2   0]
 [  0   1 116 122   1  34  62  33   1  73]
 [  0   1  76 109   0  12  32  67   2 105]
 [  3   0  14  13 342   0   0  31   4  27]
 [  1  35  22  17   0 214 111   1   2   6]
 [  0  13  71  34   0 169 130   4   6  11]
 [  0   0  12  43  44   1   0 213   2 103]
 [ 45   7  36  23  63  31  38  49  92  31]
 [  0   0  51  65   1   3  11 118   1 154]]
Accuracy: 0.4595238095238095
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.82      0.75      0.78       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.78      0.59      0.67       417
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.27      0.26      0.27       443
             Mitochondrial genetic inheritance 

In [47]:
mlp = MLPClassifier()
mlp.fit(X_train3, y_train3)
compute_metrics(y_test3, mlp.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1075: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[322  19  14   6   8  20  11   1  15   2]
 [ 27 264   5   0   0  78  33   1   9   0]
 [ 28   7 113  86  27  25  47  28  41  41]
 [ 19   1  64  84  37   9  20  67  44  59]
 [  5   0  18   9 334   1   0  31  23  13]
 [ 28  91  23   9   2 155  75   0  23   3]
 [ 44  43  68  15   5 104 125   3  29   2]
 [  1   0  14  17  54   1   2 221  39  69]
 [ 35  17  41  21  43  20  36  57 113  32]
 [  4   0  47  72  23   1   5 122  34  96]]
Accuracy: 0.435
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.63      0.77      0.69       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.60      0.63      0.61       417
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.28      0.26      0.27       443
             Mitochondrial genetic inheritance disorders - M

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [48]:
svc = SVC()
svc.fit(X_train3, y_train3)
compute_metrics(y_test3, svc.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[308  19  17  11   2  28  20   1   9   3]
 [ 11 283   5   1   0  79  34   0   4   0]
 [  7   3 140 124   2  30  56  21  13  47]
 [  2   1  84 118   9   7  26  47  14  96]
 [  3   0  16  22 324   0   2  35   7  25]
 [  5  58  26  11   0 189 110   0   4   6]
 [  8  30  73  28   0 128 152   3  13   3]
 [  0   0  16  38  29   0   2 220   2 111]
 [ 23  12  38  33  34  27  46  56 114  32]
 [  2   0  39  95   8   0   6 109  10 135]]
Accuracy: 0.47214285714285714
                                                                                   precision    recall  f1-score   support

                    Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.83      0.74      0.78       418
Mitochondrial genetic inheritance disorders - Leber's hereditary optic neuropathy       0.70      0.68      0.69       417
                     Mitochondrial genetic inheritance disorders - Leigh syndrome       0.31      0.32      0.31       443
             Mitochondrial genetic inheritance