In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [38]:
#df = pd.read_csv("train_processed.csv")
df2 = pd.read_csv("train_processed_encoded_balanced.csv")

In [39]:
df.head()

Unnamed: 0  Patient Age Genes in mother's side Inherited from father  \
0           0          2.0                    Yes                    No   
1           1          4.0                    Yes                   Yes   
2           2          6.0                    Yes                    No   
3           3         12.0                    Yes                    No   
4           4         11.0                    Yes                    No   

  Maternal gene Paternal gene  Blood cell count (mcL)  Mother's age  \
0           Yes            No                4.760603          23.0   
1            No            No                4.910669          23.0   
2            No            No                4.893297          41.0   
3           Yes            No                4.705280          21.0   
4           Yes           Yes                4.720703          32.0   

   Father's age    Status  ... Birth defects  \
0          20.0     Alive  ...      Singular   
1          23.0  Deceased  ...      Multiple   
2          22.0     Alive  ...      Singular   
3          20.0  Deceased  ...      Singular   
4          20.0     Alive  ...      Multiple   

  White Blood cell count (thousand per microliter)  Blood test result  \
0                                         9.857562  slightly abnormal   
1                                         5.522560             normal   
2                                         7.477132             normal   
3                                         7.919321       inconclusive   
4                                         4.098210  slightly abnormal   

  Symptom 1 Symptom 2 Symptom 3 Symptom 4 Symptom 5  \
0       1.0       1.0       1.0       1.0       1.0   
1       1.0       1.0       1.0       1.0       0.0   
2       0.0       1.0       1.0       1.0       1.0   
3       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0   

                               Genetic Disorder  \
0   Mitochondrial genetic inheritance disorders   
1   Mitochondrial genetic inheritance disorders   
2  Multifactorial genetic inheritance disorders   
3   Mitochondrial genetic inheritance disorders   
4  Multifactorial genetic inheritance disorders   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
1                      Cystic fibrosis  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer  

[5 rows x 31 columns]

In [40]:
df2.head()

Unnamed: 0  Patient Age  Genes in mother's side  Inherited from father  \
0           1          4.0                     1.0                    1.0   
1           2          6.0                     1.0                    0.0   
2           3         12.0                     1.0                    0.0   
3           5         14.0                     1.0                    0.0   
4           6          3.0                     1.0                    0.0   

   Maternal gene  Paternal gene  Blood cell count (mcL)  Mother's age  \
0            0.0            0.0                4.910669           5.0   
1            0.0            0.0                4.893297          23.0   
2            1.0            0.0                4.705280           3.0   
3            1.0            0.0                5.103188           5.0   
4            1.0            1.0                4.901080           5.0   

   Father's age  Status  ...  Birth defects  \
0          23.0     1.0  ...            0.0   
1          22.0     0.0  ...            1.0   
2          20.0     1.0  ...            1.0   
3          20.0     1.0  ...            0.0   
4          63.0     0.0  ...            0.0   

   White Blood cell count (thousand per microliter)  Blood test result  \
0                                          5.522560                2.0   
1                                          7.477132                2.0   
2                                          7.919321                1.0   
3                                         10.272230                2.0   
4                                          6.825974                2.0   

   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  \
0        1.0        1.0        1.0        1.0        0.0   
1        0.0        1.0        1.0        1.0        1.0   
2        0.0        0.0        1.0        0.0        0.0   
3        1.0        0.0        0.0        1.0        0.0   
4        0.0        0.0        0.0        0.0        0.0   

                               Genetic Disorder  Disorder Subclass  
0   Mitochondrial genetic inheritance disorders    Cystic fibrosis  
1  Multifactorial genetic inheritance disorders           Diabetes  
2   Mitochondrial genetic inheritance disorders     Leigh syndrome  
3              Single-gene inheritance diseases    Cystic fibrosis  
4              Single-gene inheritance diseases          Tay-Sachs  

[5 rows x 31 columns]

In [47]:
df = df.iloc[: , 1:]

In [48]:
df2 = df2.iloc[: , 1:]

In [49]:
df2['Disorder+Subclass'] = df2['Genetic Disorder'] + ' - ' + df2['Disorder Subclass']
df_train = df2.drop(["Genetic Disorder", "Disorder Subclass", "Disorder+Subclass"], axis=1)
df_test_Disorder = df2["Genetic Disorder"]
df_test_Subclass = df2["Disorder Subclass"]
df_test_Disorder_Subclass = df2["Disorder+Subclass"]


In [50]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_train_encoded = pd.DataFrame(scaler.fit_transform(df_train))

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

def compute_metrics(actual, predicted):
    #tn, fp, fn, tp = confusion_matrix(actual, predicted).ravel()
    print(confusion_matrix(actual, predicted))
    print("Accuracy: " + str(accuracy_score(actual, predicted)))
    print(classification_report(actual, predicted, zero_division=0))

In [52]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df_train_encoded, df_test_Disorder, test_size=0.30, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_train_encoded, df_test_Subclass, test_size=0.30, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(df_train_encoded, df_test_Disorder_Subclass, test_size=0.30, random_state=42)

## Predicting Genetic Disorder

In [53]:
from sklearn.linear_model import LogisticRegression

logRegression = LogisticRegression()
logRegression.fit(X_train1, y_train1)
compute_metrics(y_test1, logRegression.predict(X_test1))

[[3434   61    1]
 [ 369  188    0]
 [2157  143    3]]
Accuracy: 0.5703272498426684
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.58      0.98      0.73      3496
Multifactorial genetic inheritance disorders       0.48      0.34      0.40       557
            Single-gene inheritance diseases       0.75      0.00      0.00      2303

                                    accuracy                           0.57      6356
                                   macro avg       0.60      0.44      0.38      6356
                                weighted avg       0.63      0.57      0.44      6356



In [54]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train1, y_train1)
compute_metrics(y_test1, decisionTree.predict(X_test1))

[[2129  204 1163]
 [ 184  172  201]
 [1093  215  995]]
Accuracy: 0.5185651353052234
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.61      0.62      3496
Multifactorial genetic inheritance disorders       0.29      0.31      0.30       557
            Single-gene inheritance diseases       0.42      0.43      0.43      2303

                                    accuracy                           0.52      6356
                                   macro avg       0.45      0.45      0.45      6356
                                weighted avg       0.52      0.52      0.52      6356



In [55]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(X_train1, y_train1)
compute_metrics(y_test1, randomForest.predict(X_test1))

[[3125   34  337]
 [ 246  121  190]
 [1605   79  619]]
Accuracy: 0.6080868470736313
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.89      0.74      3496
Multifactorial genetic inheritance disorders       0.52      0.22      0.31       557
            Single-gene inheritance diseases       0.54      0.27      0.36      2303

                                    accuracy                           0.61      6356
                                   macro avg       0.56      0.46      0.47      6356
                                weighted avg       0.59      0.61      0.56      6356



In [56]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_train1, y_train1)
compute_metrics(y_test1, clf.predict(X_test1))

[[2641   77  778]
 [ 155  176  226]
 [1197  176  930]]
Accuracy: 0.5895217117684078
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.66      0.76      0.71      3496
Multifactorial genetic inheritance disorders       0.41      0.32      0.36       557
            Single-gene inheritance diseases       0.48      0.40      0.44      2303

                                    accuracy                           0.59      6356
                                   macro avg       0.52      0.49      0.50      6356
                                weighted avg       0.57      0.59      0.58      6356



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [57]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train1, y_train1)
compute_metrics(y_test1, svc.predict(X_test1))

[[3181   35  280]
 [ 234  122  201]
 [1615   74  614]]
Accuracy: 0.6162680931403398
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.63      0.91      0.75      3496
Multifactorial genetic inheritance disorders       0.53      0.22      0.31       557
            Single-gene inheritance diseases       0.56      0.27      0.36      2303

                                    accuracy                           0.62      6356
                                   macro avg       0.57      0.47      0.47      6356
                                weighted avg       0.60      0.62      0.57      6356



## Predicting Subclass

In [58]:
logRegression = LogisticRegression()
logRegression.fit(X_train2, y_train2)
compute_metrics(y_test2, logRegression.predict(X_test2))

[[ 463   78    0  482    4    2]
 [ 305  127    0  123    2    2]
 [   0    0   92   65   69  194]
 [ 202   40   29 1577  161  140]
 [  28    1   34  858  229  174]
 [   1    0   62  352  169  291]]
Accuracy: 0.43722466960352424
                        precision    recall  f1-score   support

       Cystic fibrosis       0.46      0.45      0.46      1029
              Diabetes       0.52      0.23      0.32       559
       Hemochromatosis       0.42      0.22      0.29       420
        Leigh syndrome       0.46      0.73      0.56      2149
Mitochondrial myopathy       0.36      0.17      0.23      1324
             Tay-Sachs       0.36      0.33      0.35       875

              accuracy                           0.44      6356
             macro avg       0.43      0.36      0.37      6356
          weighted avg       0.43      0.44      0.41      6356



In [59]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train2, y_train2)
compute_metrics(y_test2, decisionTree.predict(X_test2))

[[332 222   9 323 108  35]
 [197 158   2 157  33  12]
 [  9   1  84  99 108 119]
 [339 166 101 813 481 249]
 [115  43 102 455 356 253]
 [ 30   6 127 270 231 211]]
Accuracy: 0.30742605412208934
                        precision    recall  f1-score   support

       Cystic fibrosis       0.32      0.32      0.32      1029
              Diabetes       0.27      0.28      0.27       559
       Hemochromatosis       0.20      0.20      0.20       420
        Leigh syndrome       0.38      0.38      0.38      2149
Mitochondrial myopathy       0.27      0.27      0.27      1324
             Tay-Sachs       0.24      0.24      0.24       875

              accuracy                           0.31      6356
             macro avg       0.28      0.28      0.28      6356
          weighted avg       0.31      0.31      0.31      6356



In [60]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train2, y_train2)
compute_metrics(y_test2, randomForest.predict(X_test2))

[[ 387   80    0  539   21    2]
 [ 256  123    0  174    5    1]
 [   0    0   75  131   98  116]
 [ 220   31   14 1541  255   88]
 [  30    3   26  888  265  112]
 [   4    0   55  455  219  142]]
Accuracy: 0.3985210824417873
                        precision    recall  f1-score   support

       Cystic fibrosis       0.43      0.38      0.40      1029
              Diabetes       0.52      0.22      0.31       559
       Hemochromatosis       0.44      0.18      0.25       420
        Leigh syndrome       0.41      0.72      0.52      2149
Mitochondrial myopathy       0.31      0.20      0.24      1324
             Tay-Sachs       0.31      0.16      0.21       875

              accuracy                           0.40      6356
             macro avg       0.40      0.31      0.32      6356
          weighted avg       0.39      0.40      0.37      6356



In [61]:
mlp = MLPClassifier()
mlp.fit(X_train2, y_train2)
compute_metrics(y_test2, mlp.predict(X_test2))

[[ 400  150    1  420   55    3]
 [ 265  151    1  132    8    2]
 [   0    0  110   52   93  165]
 [ 284   66   62 1073  480  184]
 [  54    8   65  592  368  237]
 [  10    0  118  238  249  260]]
Accuracy: 0.37161736941472623
                        precision    recall  f1-score   support

       Cystic fibrosis       0.39      0.39      0.39      1029
              Diabetes       0.40      0.27      0.32       559
       Hemochromatosis       0.31      0.26      0.28       420
        Leigh syndrome       0.43      0.50      0.46      2149
Mitochondrial myopathy       0.29      0.28      0.29      1324
             Tay-Sachs       0.31      0.30      0.30       875

              accuracy                           0.37      6356
             macro avg       0.36      0.33      0.34      6356
          weighted avg       0.37      0.37      0.37      6356



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [62]:
svc = SVC()
svc.fit(X_train2, y_train2)
compute_metrics(y_test2, svc.predict(X_test2))

[[ 448   70    0  500   11    0]
 [ 284  115    0  156    3    1]
 [   0    0   65  114   76  165]
 [ 219   31   22 1548  221  108]
 [  33    2   26  893  227  143]
 [   2    0   46  434  168  225]]
Accuracy: 0.4134675896790434
                        precision    recall  f1-score   support

       Cystic fibrosis       0.45      0.44      0.44      1029
              Diabetes       0.53      0.21      0.30       559
       Hemochromatosis       0.41      0.15      0.22       420
        Leigh syndrome       0.42      0.72      0.53      2149
Mitochondrial myopathy       0.32      0.17      0.22      1324
             Tay-Sachs       0.35      0.26      0.30       875

              accuracy                           0.41      6356
             macro avg       0.41      0.32      0.34      6356
          weighted avg       0.41      0.41      0.38      6356



# Predicting Disorder + Subclass

In [63]:
logRegression = LogisticRegression()
logRegression.fit(X_train3, y_train3)
compute_metrics(y_test3, logRegression.predict(X_test3))

[[   0    0    0   38    1    0    6    0   41    0    0    1]
 [   0    0    0   11    0    0   12    0   30    0    0    0]
 [   0    0    0    6    7    0    0    0    0   12    0   15]
 [   0    0    0 1352  252    0   19    0  180   13    0   81]
 [   0    0    0  754  366    0    2    0   35   37    0  130]
 [   0    0    0   38   21    0    0    0    0    7    0   29]
 [   0    0    0  100    2    0  119    0  283    0    0    2]
 [   0    0    0   14    0    0   12    0   24    0    0    1]
 [   0    0    0  401    7    0   75    0  458    0    0    1]
 [   0    0    0   42  100    0    0    0    0   82    0  156]
 [   0    0    0   78   36    0    8    0   35   18    0   26]
 [   0    0    0  256  250    0    0    0    2   56    0  216]]
Accuracy: 0.407960981749528
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.00      0.00      0.00     

In [64]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train3, y_train3)
compute_metrics(y_test3, decisionTree.predict(X_test3))

[[  5   0   0  22  11   0  18   4  17   0   5   5]
 [  1   2   0   7   5   1  13   1  18   0   3   2]
 [  0   0   2  10  12   2   0   0   1   6   0   7]
 [ 30   9  11 634 422  33 111  11 264  73  90 209]
 [ 17   6  16 448 353  23  29   3  98  74  55 202]
 [  0   1   3  24  28   2   0   0   5  11   2  19]
 [ 16  17   0  94  35   1 138  16 163   1  21   4]
 [  4   1   0   5   4   0  15   0  19   1   2   0]
 [ 22  18   3 251  90   3 188  19 278   4  38  28]
 [  0   0   7  85  78   8   0   3   5  77  19  98]
 [  6   1   0  56  42   4  17   1  31  14   2  27]
 [  5   2  12 190 202  14  12   1  24 103  36 179]]
Accuracy: 0.263058527375708
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.05      0.06      0.05        87
              Mitochondrial genetic inheritance disorders - Diabetes       0.04      0.04      0.04        53
       Mitochondrial genetic

In [65]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train3, y_train3)
compute_metrics(y_test3, randomForest.predict(X_test3))

[[   0    0    0   50    3    0    5    0   28    0    0    1]
 [   0    0    0   15    0    0   12    0   26    0    0    0]
 [   0    0    0   10    8    0    0    0    0    9    0   13]
 [   0    0    0 1292  325    0   22    0  178   10    0   70]
 [   0    0    0  794  354    0    4    0   35   29    0  108]
 [   0    0    0   49   27    0    0    0    0    4    0   15]
 [   0    1    0  126    8    0  122    0  248    1    0    0]
 [   0    0    0   10    1    0   11    0   28    0    0    1]
 [   0    0    0  441   23    0  106    0  370    0    0    2]
 [   0    0    0  105  109    0    0    0    0   56    0  110]
 [   0    0    0   90   44    0    7    0   30    8    0   22]
 [   0    0    1  323  274    0    0    0    3   45    1  133]]
Accuracy: 0.3661107614852108
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.00      0.00      0.00    

In [66]:
mlp = MLPClassifier()
mlp.fit(X_train3, y_train3)
compute_metrics(y_test3, mlp.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[   1    1    0   30    6    0   11    0   37    0    0    1]
 [   0    0    0   11    0    0   14    0   28    0    0    0]
 [   0    0    0    3   14    0    0    0    1   11    2    9]
 [   1    1    1 1062  406    1   41    3  222   39    2  118]
 [   1    0    3  650  357    4    8    0   43   69    4  185]
 [   0    0    0   31   24    0    0    0    0   15    0   25]
 [   1    3    0   94   12    0  156    5  234    0    0    1]
 [   0    2    0   14    1    0   13    1   19    0    0    1]
 [   0    0    0  350   36    0  148    4  403    0    1    0]
 [   0    0    1   66   82    1    0    0    0  109    4  117]
 [   0    1    0   61   45    0   11    3   33   18    1   28]
 [   0    0    1  226  233    2    0    0    7  111    3  197]]
Accuracy: 0.35981749528005036
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.25      0.01      0.02   

In [67]:
svc = SVC()
svc.fit(X_train3, y_train3)
compute_metrics(y_test3, svc.predict(X_test3))

[[   0    0    0   43    2    0    3    0   39    0    0    0]
 [   0    0    0   11    0    0    8    0   34    0    0    0]
 [   0    0    0    6   12    0    0    0    0    6    0   16]
 [   0    0    0 1288  322    0   18    0  196   10    0   63]
 [   0    0    0  764  369    0    3    0   38   22    0  128]
 [   0    0    0   43   25    0    0    0    0    6    0   21]
 [   0    0    0  103    6    0  104    0  292    0    0    1]
 [   0    0    0   11    1    0   13    0   25    0    0    1]
 [   0    0    0  400   13    0   71    0  458    0    0    0]
 [   0    0    0   70  116    0    0    0    0   60    0  134]
 [   0    0    0   89   37    0    4    0   38   11    0   22]
 [   0    0    0  278  269    0    0    0    3   39    0  191]]
Accuracy: 0.3886091881686595
                                                                      precision    recall  f1-score   support

       Mitochondrial genetic inheritance disorders - Cystic fibrosis       0.00      0.00      0.00    