In [173]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [174]:
df = pd.read_csv("train_processed.csv")
df2 = pd.read_csv("train_processed_encoded.csv")

In [175]:
df.head()

Unnamed: 0  Patient Age Genes in mother's side Inherited from father  \
0           0          2.0                    Yes                    No   
1           1          4.0                    Yes                   Yes   
2           2          6.0                    Yes                    No   
3           3         12.0                    Yes                    No   
4           4         11.0                    Yes                    No   

  Maternal gene Paternal gene  Blood cell count (mcL)  Mother's age  \
0           Yes            No                4.760603          23.0   
1            No            No                4.910669          23.0   
2            No            No                4.893297          41.0   
3           Yes            No                4.705280          21.0   
4           Yes           Yes                4.720703          32.0   

   Father's age    Status  ... Birth defects  \
0          20.0     Alive  ...      Singular   
1          23.0  Deceased  ...      Multiple   
2          22.0     Alive  ...      Singular   
3          20.0  Deceased  ...      Singular   
4          20.0     Alive  ...      Multiple   

  White Blood cell count (thousand per microliter)  Blood test result  \
0                                         9.857562  slightly abnormal   
1                                         5.522560             normal   
2                                         7.477132             normal   
3                                         7.919321       inconclusive   
4                                         4.098210  slightly abnormal   

  Symptom 1 Symptom 2 Symptom 3 Symptom 4 Symptom 5  \
0       1.0       1.0       1.0       1.0       1.0   
1       1.0       1.0       1.0       1.0       0.0   
2       0.0       1.0       1.0       1.0       1.0   
3       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0   

                               Genetic Disorder  \
0   Mitochondrial genetic inheritance disorders   
1   Mitochondrial genetic inheritance disorders   
2  Multifactorial genetic inheritance disorders   
3   Mitochondrial genetic inheritance disorders   
4  Multifactorial genetic inheritance disorders   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
1                      Cystic fibrosis  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer  

[5 rows x 31 columns]

In [176]:
df2.head()

Unnamed: 0  Patient Age  Genes in mother's side  Inherited from father  \
0           0          2.0                     1.0                    0.0   
1           1          4.0                     1.0                    1.0   
2           2          6.0                     1.0                    0.0   
3           3         12.0                     1.0                    0.0   
4           4         11.0                     1.0                    0.0   

   Maternal gene  Paternal gene  Blood cell count (mcL)  Mother's age  \
0            1.0            0.0                4.760603           5.0   
1            0.0            0.0                4.910669           5.0   
2            0.0            0.0                4.893297          23.0   
3            1.0            0.0                4.705280           3.0   
4            1.0            1.0                4.720703          14.0   

   Father's age  Status  ...  Birth defects  \
0          20.0     0.0  ...            1.0   
1          23.0     1.0  ...            0.0   
2          22.0     0.0  ...            1.0   
3          20.0     1.0  ...            1.0   
4          20.0     0.0  ...            0.0   

   White Blood cell count (thousand per microliter)  Blood test result  \
0                                          9.857562                3.0   
1                                          5.522560                2.0   
2                                          7.477132                2.0   
3                                          7.919321                1.0   
4                                          4.098210                3.0   

   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Symptom 5  Genetic Disorder  \
0        1.0        1.0        1.0        1.0        1.0               0.0   
1        1.0        1.0        1.0        1.0        0.0               0.0   
2        0.0        1.0        1.0        1.0        1.0               1.0   
3        0.0        0.0        1.0        0.0        0.0               0.0   
4        0.0        0.0        0.0        0.0        0.0               1.0   

   Disorder Subclass  
0                5.0  
1                2.0  
2                3.0  
3                6.0  
4                1.0  

[5 rows x 31 columns]

In [177]:
df = df.iloc[: , 1:]

In [178]:
df2 = df2.iloc[: , 1:]

In [179]:
df2['Disorder+Subclass'] = df['Genetic Disorder'] + ' - ' + df['Disorder Subclass']
df_train = df2.drop(["Genetic Disorder", "Disorder Subclass", "Disorder+Subclass"], axis=1)
df_test_Disorder = df2["Genetic Disorder"]
df_test_Subclass = df2["Disorder Subclass"]
df_test_Disorder_Subclass = df2["Disorder+Subclass"]


In [180]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_train_encoded = pd.DataFrame(scaler.fit_transform(df_train))

In [187]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

def compute_metrics(actual, predicted):
    #tn, fp, fn, tp = confusion_matrix(actual, predicted).ravel()
    print(confusion_matrix(actual, predicted))
    print("Accuracy: " + str(accuracy_score(actual, predicted)))
    print(classification_report(actual, predicted, zero_division=0))

In [188]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df_train_encoded, df_test_Disorder, test_size=0.30, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_train_encoded, df_test_Subclass, test_size=0.30, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(df_train_encoded, df_test_Disorder_Subclass, test_size=0.30, random_state=42)

## Predicting Genetic Disorder

In [189]:
from sklearn.linear_model import LogisticRegression

logRegression = LogisticRegression()
logRegression.fit(X_train1, y_train1)
compute_metrics(y_test1, logRegression.predict(X_test1))

[[3620  109    0]
 [ 538  116    0]
 [2192   50    0]]
Accuracy: 0.5639245283018868
              precision    recall  f1-score   support

         0.0       0.57      0.97      0.72      3729
         1.0       0.42      0.18      0.25       654
         2.0       0.00      0.00      0.00      2242

    accuracy                           0.56      6625
   macro avg       0.33      0.38      0.32      6625
weighted avg       0.36      0.56      0.43      6625



In [190]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train1, y_train1)
compute_metrics(y_test1, decisionTree.predict(X_test1))

[[2222  271 1236]
 [ 246  180  228]
 [1126  230  886]]
Accuracy: 0.49630188679245285
              precision    recall  f1-score   support

         0.0       0.62      0.60      0.61      3729
         1.0       0.26      0.28      0.27       654
         2.0       0.38      0.40      0.39      2242

    accuracy                           0.50      6625
   macro avg       0.42      0.42      0.42      6625
weighted avg       0.50      0.50      0.50      6625



In [191]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(X_train1, y_train1)
compute_metrics(y_test1, randomForest.predict(X_test1))

[[3371   60  298]
 [ 400  100  154]
 [1720   40  482]]
Accuracy: 0.5966792452830189
              precision    recall  f1-score   support

         0.0       0.61      0.90      0.73      3729
         1.0       0.50      0.15      0.23       654
         2.0       0.52      0.21      0.30      2242

    accuracy                           0.60      6625
   macro avg       0.54      0.42      0.42      6625
weighted avg       0.57      0.60      0.54      6625



In [192]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_train1, y_train1)
compute_metrics(y_test1, clf.predict(X_test1))

[[2733  188  808]
 [ 252  210  192]
 [1292  173  777]]
Accuracy: 0.5615094339622642
              precision    recall  f1-score   support

         0.0       0.64      0.73      0.68      3729
         1.0       0.37      0.32      0.34       654
         2.0       0.44      0.35      0.39      2242

    accuracy                           0.56      6625
   macro avg       0.48      0.47      0.47      6625
weighted avg       0.54      0.56      0.55      6625



/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [193]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train1, y_train1)
compute_metrics(y_test1, svc.predict(X_test1))

[[3406  103  220]
 [ 447  124   83]
 [1823   53  366]]
Accuracy: 0.5880754716981133
              precision    recall  f1-score   support

         0.0       0.60      0.91      0.72      3729
         1.0       0.44      0.19      0.27       654
         2.0       0.55      0.16      0.25      2242

    accuracy                           0.59      6625
   macro avg       0.53      0.42      0.41      6625
weighted avg       0.57      0.59      0.52      6625



## Predicting Subclass

In [194]:
logRegression = LogisticRegression()
logRegression.fit(X_train2, y_train2)
compute_metrics(y_test2, logRegression.predict(X_test2))

[[   4    0   10   18    0   10    3    0    0]
 [   0    0    0    0   22    0    1    1    9]
 [   0    0  459   57    0    6  474    6    4]
 [   0    0  344   94    0   13  128    0    2]
 [   0    4    0    0   93    0   73   53  170]
 [   0    0  102   57    0   30   22    0    0]
 [   0    0  254   30   26    2 1586  163  120]
 [   0    0   30    1   21    0  875  235  176]
 [   0    0    3    0   54    0  355  181  244]]
Accuracy: 0.4143396226415094
              precision    recall  f1-score   support

         0.0       1.00      0.09      0.16        45
         1.0       0.00      0.00      0.00        33
         2.0       0.38      0.46      0.42      1006
         3.0       0.37      0.16      0.22       581
         4.0       0.43      0.24      0.31       393
         5.0       0.49      0.14      0.22       211
         6.0       0.45      0.73      0.56      2181
         7.0       0.37      0.18      0.24      1338
         8.0       0.34      0.29      0.31       8

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [195]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train2, y_train2)
compute_metrics(y_test2, decisionTree.predict(X_test2))

[[  4   0  10   9   0  14   8   0   0]
 [  0   3   0   0  11   0   4   3  12]
 [ 12   0 282 187   7  52 327 104  35]
 [ 22   0 181 142   2  62 128  36   8]
 [  0  13   5   0  77   0 103  88 107]
 [ 13   0  65  65   0  32  26   7   3]
 [  8   5 339 155 107  43 793 488 243]
 [  0   4 120  38 110   9 465 362 230]
 [  0   3  37  12 112   1 244 222 206]]
Accuracy: 0.28694339622641507
              precision    recall  f1-score   support

         0.0       0.07      0.09      0.08        45
         1.0       0.11      0.09      0.10        33
         2.0       0.27      0.28      0.28      1006
         3.0       0.23      0.24      0.24       581
         4.0       0.18      0.20      0.19       393
         5.0       0.15      0.15      0.15       211
         6.0       0.38      0.36      0.37      2181
         7.0       0.28      0.27      0.27      1338
         8.0       0.24      0.25      0.25       837

    accuracy                           0.29      6625
   macro avg       0.2

In [196]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train2, y_train2)
compute_metrics(y_test2, randomForest.predict(X_test2))

[[   0    0   20   20    0    1    4    0    0]
 [   0    0    0    0   15    0    5    3   10]
 [   0    0  381   69    1    6  514   33    2]
 [   0    0  278  101    0    7  191    4    0]
 [   0    0    0    0   59    0  139   84  111]
 [   0    0  107   61    0   10   33    0    0]
 [   0    0  224   45   19    0 1558  232  103]
 [   0    0   33    2   22    0  929  238  114]
 [   0    1    3    0   44    0  441  198  150]]
Accuracy: 0.3769056603773585
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        45
         1.0       0.00      0.00      0.00        33
         2.0       0.36      0.38      0.37      1006
         3.0       0.34      0.17      0.23       581
         4.0       0.37      0.15      0.21       393
         5.0       0.42      0.05      0.09       211
         6.0       0.41      0.71      0.52      2181
         7.0       0.30      0.18      0.22      1338
         8.0       0.31      0.18      0.23       8

In [197]:
mlp = MLPClassifier()
mlp.fit(X_train2, y_train2)
compute_metrics(y_test2, mlp.predict(X_test2))

[[   9    0    6   17    0    9    4    0    0]
 [   0    4    0    0   15    0    3    4    7]
 [   6    0  388  113    1   28  412   53    5]
 [   7    0  255  125    0   43  143    7    1]
 [   0    9    0    0  127    0   76   86   95]
 [  13    0   64   66    0   37   29    2    0]
 [   2    0  272   63   55   22 1217  422  128]
 [   0    1   62    7   76    1  666  353  172]
 [   0    6    3    0   97    0  303  237  191]]
Accuracy: 0.3699622641509434
              precision    recall  f1-score   support

         0.0       0.24      0.20      0.22        45
         1.0       0.20      0.12      0.15        33
         2.0       0.37      0.39      0.38      1006
         3.0       0.32      0.22      0.26       581
         4.0       0.34      0.32      0.33       393
         5.0       0.26      0.18      0.21       211
         6.0       0.43      0.56      0.48      2181
         7.0       0.30      0.26      0.28      1338
         8.0       0.32      0.23      0.27       8

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [198]:
svc = SVC()
svc.fit(X_train2, y_train2)
compute_metrics(y_test2, svc.predict(X_test2))

[[   0    0   10   32    0    0    3    0    0]
 [   0    0    0    0   16    0    4    2   11]
 [   0    0  462   53    0    0  469   21    1]
 [   0    0  324  100    0    1  155    0    1]
 [   0    0    0    0   75    0  109   63  146]
 [   0    0  117   67    0    2   25    0    0]
 [   0    0  290   24   19    0 1553  188  107]
 [   0    0   41    0   16    0  917  203  161]
 [   0    0    4    0   31    0  427  175  200]]
Accuracy: 0.39169811320754716
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        45
         1.0       0.00      0.00      0.00        33
         2.0       0.37      0.46      0.41      1006
         3.0       0.36      0.17      0.23       581
         4.0       0.48      0.19      0.27       393
         5.0       0.67      0.01      0.02       211
         6.0       0.42      0.71      0.53      2181
         7.0       0.31      0.15      0.20      1338
         8.0       0.32      0.24      0.27       

# Predicting Disorder + Subclass

In [199]:
logRegression = LogisticRegression()
logRegression.fit(X_train3, y_train3)
compute_metrics(y_test3, logRegression.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[   0    0    0    0    0    2    2    0    0    0    0    2    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     2    0    1]
 [   0    0    0    0    0    2   42    2    0    0    0    5    0   37
     0    0    0]
 [   0    0    0    0    0    2    8    0    0    0    0    6    0   31
     0    0    0]
 [   0    0    0    0    0    0    7    9    0    0    0    0    0    0
    11    0   14]
 [   0    0    0    0    0   33   18    0    0    1    0   58    0  101
     0    0    0]
 [   0    0    0    0    0    1 1377  242    0    0    0   15    0  201
    12    0   68]
 [   0    0    0    0    0    0  787  363    0    0    0    1    0   36
    24    0  127]
 [   0    0    0    0    0    0   32   25    0    0    0    0    0    0
     6    0   16]
 [   0    0    0    0    0   12    1    0    0    2    0   15    0    9
     0    0    0]
 [   0    0    0    0    0    0    1    3    0    0    2    0    0    0
    19    0    5]
 [   0    

In [200]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train3, y_train3)
compute_metrics(y_test3, decisionTree.predict(X_test3))

[[  0   0   3   0   0   1   0   0   0   0   0   2   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   1   0   1]
 [  0   0   1   2   0   3  35  12   2   1   0  10   1  15   1   2   3]
 [  0   0   3   0   0   6   8   3   0   1   0   8   2  12   0   2   2]
 [  0   0   1   0   0   0  11  11   1   0   0   0   0   2   7   2   6]
 [  1   0   7   7   0  35  22   5   1  10   0  53   4  60   0   3   3]
 [  0   0  25  11   5  17 723 392  31   1   2  89  13 273  72  59 203]
 [  0   0  14   4   4   7 450 348  28   1   4  32   5  90  95  51 205]
 [  0   0   0   0   0   0  16  23   2   0   0   1   0   5  16   1  15]
 [  0   0   1   0   0   6   3   0   0   5   0  13   0   9   0   2   0]
 [  0   0   0   0   0   0   5   5   0   0   5   0   0   1   5   3   6]
 [  4   0  18  13   0  52 100  27   1  12   0  98  13 172   1  14   9]
 [  0   0   2   1   0   2   4   3   0   5   0  12   3  15   0   1   3]
 [  1   0  22  19   0  48 270  78   2   5   1 136  11 265   5  30  25]
 [  0 

In [201]:
randomForest = RandomForestClassifier()
randomForest.fit(X_train3, y_train3)
compute_metrics(y_test3, randomForest.predict(X_test3))

[[   0    0    0    0    0    0    1    0    0    0    0    3    0    2
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     2    0    1]
 [   0    0    0    0    0    1   51    5    0    0    0    4    0   27
     0    0    0]
 [   0    0    0    0    0    1   14    1    0    0    0    8    0   23
     0    0    0]
 [   0    0    0    0    0    0   12   12    0    0    0    0    0    1
     6    0   10]
 [   0    0    0    0    0   23   26    1    0    0    0   53    0  108
     0    0    0]
 [   0    0    0    0    0    1 1328  320    0    0    0   23    0  175
    12    0   57]
 [   0    0    0    0    0    0  845  349    0    0    0    5    0   31
    21    0   87]
 [   0    0    0    0    0    0   38   19    0    0    0    0    0    0
     6    0   16]
 [   0    0    0    0    0    4    2    0    0    1    0   20    0   12
     0    0    0]
 [   0    0    0    0    0    0    3    7    0    0    0    0    0    0
    12    0    8]
 [   0    

In [202]:
mlp = MLPClassifier()
mlp.fit(X_train3, y_train3)
compute_metrics(y_test3, mlp.predict(X_test3))

/Users/lucasmarch/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:676: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[   0    0    0    0    0    1    1    0    0    0    0    2    0    2
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     2    0    1]
 [   0    0    0    1    0    1   38    8    0    2    0    6    1   30
     0    0    1]
 [   0    0    0    0    0    2   10    1    0    0    0   14    2   18
     0    0    0]
 [   0    0    0    0    0    0    5    8    0    0    1    0    0    2
    11    1   13]
 [   1    0    0    1    0   42   20    0    0    7    0   60    1   77
     0    2    0]
 [   0    0    2    1    1    7 1128  374    2    1    0   49    0  199
    33    4  115]
 [   0    0    0    1    2    0  668  347    1    0    1   13    1   47
    52    2  203]
 [   0    0    0    0    1    0   25   26    2    0    0    0    0    0
     6    0   19]
 [   0    0    0    1    0    9    1    0    0    7    0   13    1    7
     0    0    0]
 [   0    0    0    0    1    0    2    2    0    0    6    0    0    0
    13    0    6]
 [   1    

In [203]:
svc = SVC()
svc.fit(X_train3, y_train3)
compute_metrics(y_test3, svc.predict(X_test3))

[[   0    0    0    0    0    0    1    0    0    0    0    3    0    2
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     1    0    2]
 [   0    0    0    0    0    0   42    4    0    0    0    4    0   38
     0    0    0]
 [   0    0    0    0    0    0   10    0    0    0    0    9    0   28
     0    0    0]
 [   0    0    0    0    0    0    9   13    0    0    0    0    0    0
     8    0   11]
 [   0    0    0    0    0    5   22    0    0    0    0   69    0  115
     0    0    0]
 [   0    0    0    0    0    0 1298  305    0    0    0   16    0  224
     9    0   64]
 [   0    0    0    0    0    0  793  347    0    0    0    1    0   46
    13    0  138]
 [   0    0    0    0    0    0   35   24    0    0    0    0    0    0
     2    0   18]
 [   0    0    0    0    0    0    1    0    0    0    0   27    0   11
     0    0    0]
 [   0    0    0    0    0    0    2    4    0    0    0    0    0    0
    16    0    8]
 [   0    